/*	Copyright (c) 1984 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)kern-port:os/getsizes.c	10.6"
#include "sys/types.h"
#include "sys/param.h"
#include "sys/psw.h"
#include "sys/immu.h"
#include "sys/buf.h"
#include "sys/tty.h"
#include "sys/file.h"
#include "sys/inode.h"
#include "sys/region.h"
#include "sys/proc.h"
#include "sys/map.h"
#include "sys/callo.h"
#include "sys/mount.h"
#include "sys/fcntl.h"
#include "sys/flock.h"
#include "sys/pcb.h"
#include "sys/fs/s5dir.h"
#include "sys/signal.h"
#include "sys/user.h"
#include "sys/pfdat.h"
#include "sys/var.h"
#include "sys/tuneable.h"
#include "sys/conf.h"
#include "sys/ipc.h"
#include "sys/msg.h"
#include "sys/sem.h"
#include "sys/shm.h"
#include "sys/swap.h"
#include "sys/iobuf.h"
#include "sys/fs/s5fblk.h"
#include "sys/fs/s5filsys.h"
#include "sys/fs/s5inode.h"
#include "sys/fs/s5macros.h"
#include "sys/fs/s5param.h"
#include "sys/adv.h"
#include "sys/nserve.h"
#include "sys/sema.h"
#include "sys/comm.h"
#include "sys/dirent.h"
#include "sys/ino.h"
#include "sys/message.h"
#include "sys/nami.h"
#include "sys/stream.h"
