#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)setmnt:setmnt.mk	1.2"

#	Makefile for setmnt 

ROOT =

DIR = $(ROOT)/etc

INC = $(ROOT)/usr/include

LDFLAGS = -s 

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = setmnt.mk


MAINS = setmnt

OBJECTS =  setmnt.o

SOURCES =  setmnt.c

ALL:		$(MAINS)

setmnt:		setmnt.o 
	$(CC) $(CFLAGS)  -o setmnt  setmnt.o   $(LDFLAGS)


setmnt.o:	 $(INC)/sys/param.h $(INC)/signal.h	\
		 $(INC)/sys/signal.h $(INC)/sys/types.h \
		 $(INC)/sys/sysmacros.h $(INC)/sys/filsys.h	\
		 $(INC)/mnttab.h 

GLOBALINCS = $(INC)/mnttab.h $(INC)/signal.h \
	$(INC)/sys/filsys.h $(INC)/sys/param.h \
	$(INC)/sys/signal.h $(INC)/sys/sysmacros.h \
	$(INC)/sys/types.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset $(MAINS) $(DIR)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
