.TH LOGNAME 1
.SH NAME
logname \- get login name
.SH SYNOPSIS
.B logname
.SH DESCRIPTION
.I Logname\^
returns the contents of the environment variable
.SM \fB$LOGNAME\fP,
which is set when a
user logs into the system.
.SH FILES
/etc/profile
.SH SEE ALSO
env(1), login(1).
.br
logname(3X), environ(5) in the
\f2\s-1UNIX\s+1 System V Programmer Reference Manual\fR.
.\"	@(#)logname.1	6.2 of 9/2/83
