.TH NOHUP 1
.SH NAME
nohup \- run a command immune to hangups and quits
.SH SYNOPSIS
.B nohup
command [ arguments ]
.SH DESCRIPTION
.I Nohup\^
executes
.I command\^
with hangups
and quits ignored.
If output is not re-directed by the user,
both standard output and standard error are sent to
.BR nohup.out .
If
.B nohup.out
is not writable in the current directory,
output is redirected to
.BR \s-1$HOME\s+1/nohup.out .
.SH EXAMPLE
It is frequently desirable to apply 
.IR nohup
to pipelines or lists of commands.
This can be done only by placing pipelines and command lists in a 
single file, called a shell procedure.
One can then issue:
.sp
.RS
nohup sh file
.RE
.sp
and the 
.IR nohup
applies to everything in 
.IR file.
If the shell procedure
.I file 
is to be executed often, 
then the need to type  
.IR sh
can be eliminated by giving
.IR file 
execute permission.
Add an ampersand and the contents of
.I file
are run in the background with interrupts also ignored [see 
.IR sh (1)]:
.sp
.RS
nohup file &
.RE
.sp
An example of what the contents of 
.IR file
could be is:
.sp
.RS
tbl ofile | eqn | nroff > nfile
.RE
.SH SEE ALSO
chmod(1), nice(1), sh(1).
.br
signal(2) in the
\f2\s-1UNIX\s+1 System V Programmer Reference Manual\fR.
.SH WARNINGS
nohup command1; command2~~~~~
.IR nohup 
applies only to
.IR command1
.br
nohup (command1; command2)	is syntactically incorrect.
.sp
Be careful of where standard error is redirected.
The following command may put error messages on tape,
making it unreadable:
.sp
		nohup cpio \-o <list >/dev/rmt/1m&
.br
while
.br
		nohup cpio \-o <list >/dev/rmt/1m 2>errors&
.sp
puts the error messages into file
.IR errors .
.\"	@(#)nohup.1	6.3 of 9/2/83
