.TH PWD 1
.SH NAME
pwd \- working directory name
.SH SYNOPSIS
.B pwd
.SH DESCRIPTION
.I Pwd\^
prints the path name of the working (current) directory.
.SH "SEE ALSO"
cd(1).
.SH DIAGNOSTICS
``Cannot open ..'' and ``Read error in ..'' indicate
possible file system trouble and should be
referred to a \s-1UNIX\s0 system programming counselor.
.\"	@(#)pwd.1	6.2 of 9/2/83
