.TH TIME 1 
.SH NAME
time \- time a command
.SH SYNOPSIS
.B time
command
.SH DESCRIPTION
The
\fIcommand\fP is executed; after it is complete,
.I time\^
prints the elapsed time during the command, the time
spent in the system, and the time spent in execution
of the command.
Times are reported in seconds.
.PP
The times are printed on standard error.
.SH SEE ALSO
timex(1).
.br
times(2) in the
\f2\s-1UNIX\s+1 System V Programmer Reference Manual\fR.
.\"	@(#)time.1	6.1 of 5/4/83


