.TH WHAT 1
.SH NAME
what \- identify \s-1SCCS\s+1 files
.SH SYNOPSIS
.B what
.RB [ \-s ]
files
.SH DESCRIPTION
.I What\^
searches the given files for all occurrences
of the pattern that
.IR get (1)
substitutes for %\&Z% (this is
\fB@\&(#)\fR
at this printing)
and prints out what follows until the
first
.BR ~ ,
.BR > ,
new-line,
.BR \e ,
or null character.
For example, if the C program in file \fBf.c\fR contains
.PP
.RS 5
char ident[] = "\|@\&(#)identification information\|";
.RE
.PP
and \fBf.c\fR is compiled to yield \fBf.o\fR and \fBa.out\fR,
then the command
.PP
.RS 5
what\|
.RB f . c\|
.RB f . o\|
.RB a . out
.RE
.PP
will print
.PP
.RS 5
.TP 8
f\fB.\fRc:
.br
identification information
.TP 8
f\fB.\fRo:
.br
identification information
.TP 8
a\fB.\fRout:
.br
identification information
.RE
.PP
.I What\^
is intended to be used in conjunction with the \*(S) command
.IR get (1),
which automatically inserts identifying information,
but it can also be used where the information is inserted manually.
Only one option exists:
.AR s Quit
after finding the first occurrence of pattern in each file.
.SH SEE ALSO
get(1), help(1).
.SH DIAGNOSTICS
Exit status is 0 if any matches are found, otherwise 1.  Use
.IR help (1)
for explanations.
.SH BUGS
It is possible that an unintended occurrence of the pattern
.B @\&(#)
could be
found just by chance, but this causes no harm in nearly all cases.
.tr ~~
.\"	@(#)what.1	6.2 of 9/2/83
