/*	Copyright (c) 1984 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)xt:xtstats.c	2.4"

/*	Copyright (c) 1984 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

/*
**	Routine to print 'xt' driver statistics
*/

#include	"stdio.h"
#include	"errno.h"
#include	"sys/types.h"
#include	"sys/tty.h"
#include	"sys/jioctl.h"
#include	"sys/xtproto.h"
#include	"sys/xt.h"

#define Fprintf (void)fprintf

#if	XTSTATS == 1
Stats_t		Stats[S_NSTATS];

char *		Descs[S_NSTATS]	=
{
	 "packets transmitted"
	,"packets received"
	,"CRC errors"
	,"bad ack"
	,"bad nak"
	,"packets out of sequence"
	,"retransmissions generated by naks"
	,"duplicate packets received"
	,"naks received"
	,"naks transmitted"
	,"acks received"
	,"acks transmitted"
	,"packets with bad headers"
	,"packets with bad size"
	,"acks not received"
	,"bad control packets"
	,"bad control data packets"
	,"system free list empty"
	,"received packets with command size/data size mismatch"
	,"received packets with channel out of range"
	,"received packets with unrecognised command"
	,"channel 0 receive buffer unavailable for command"
	,"receive packets terminated by timeout"
	,"retransmissions generated by timeouts"
	,"wakeups for wflushes"
	,"wakeups for writes"
};

extern long		time();
extern char *		ctime();

#define	SYSERROR	(-1)
#endif



int
xtstats(name, cfd, ofd)
	char *name;
	int   cfd;
	register FILE *	ofd;
{
#if	XTSTATS == 1
	register long	l;
	register int	i;
	register int	count = 0;

	if ( ioctl(cfd, XTIOCSTATS, Stats) == SYSERROR ) {
		Fprintf(stderr,"%s: xt ioctl failed - errno '%d'\n",name,errno);
		return(1);
	}

	for ( i = 0 ; i < S_NSTATS ; i++ )
		if ( l = Stats[i] )
		{
			if ( count++ == 0 )
			{
				long	t;

				(void)time(&t);
				(void)fprintf(ofd, "\n%15.15s Xt Statistics:-\n", ctime(&t)+4);
			}
			(void)fprintf(ofd, "%11ld %s\n", l, Descs[i]);
		}
	if ( count )
		(void)fflush(ofd);
	return(0);
#endif
}
