00000nroff
00703100130NAME(S) OF INPUT FILE(S):
01705100001REDIRECT OUTPUT TO:
02707100001SPECIFY TYPE OF OUTPUT TERMINAL [-T]:
03709100001INCLUDE MEMORANDUM MACROS [-mm] (y/n):
04711100001INCLUDE MAN MACROS [-man] (y/n):
05713100001INCLUDE PERMUTED INDEX MACROS [-mptx] (y/n):
06715100001SPECIFY PAGES TO BE PRINTED [-o] (n-m):
07717100001SET NUMBER FOR FIRST PAGE [-n]:
08719100001SET PAGE STOP [-s]:
09721100030SET REGISTER [-raN]:
10723100001SPECIFY TO READ STANDARD INPUT AFTER FILES [-i] (y/n):
11725100001SPECIFY TO READ INSERTIONS FROM STANDARD INPUT [-q] (y/n):
12727100001SPECIFY TO PRINT TERMINAL MESSAGES ONLY [-z] (y/n):
13729100001PRINT EQUALLY SPACED WORDS [-e] (y/n):
14731100001USE TABS DURING HORIZONTAL SPACING [-h] (y/n):
15733100001SET EMBOLDENING FACTOR [-u]:
16735100030ADDITIONS TO THE COMMAND LINE:

00130
01150
02020
03000
04000
05000
06040
07050
08060
09070
10080
11090
12100
13110
14120
15140
16162


nroff is a text processor that accepts lines of text 
interspersed with lines of format control information.
nroff formats the text into a printable, paginated 
document having a user-designed style for printing
on typewriter-like devices and line printers.

00Enter the name(s) of file(s) whose contents you want formatted.
If you enter multiple files, the command will format each in the
order specified. nroff reads standard input when you use a hyphen (-)
instead of any file names.
01If you type a file name here, the output of this command will go to the
file.  ASSIST will warn you if the file already exists.  If it exists,
redirecting output to it will destroy the previous contents of the file.
(See the UNIX walkthru for a more complete discussion of redirection.)
02The argument for -T is the desired terminal type.  This option
prepares output for a specified terminal.
These are the recognized terminal types:

2631         300-12        382         832        X
2631-c       300s          4000a       8510
2631-e       300s-12       450         lp
300          37            450-12      tn300

However, since ASSIST does not perform any error checking on this
field, you should use it with caution.
03This option reads in the memorandum macro package.  This package
provides a formatting capability for a very wide variety of documents.
please see the following reference for further details "The Macro 
Package mm: a Tutorial" in the UNIX DOCUMENTER'S WORKBENCH Software 
User's Guide.  [-mm]
04The man macros are used to format UNIX system manual pages.
[-man]
05The mptx macro package is used to format permuted indexes.
[-mptx]
06Print only pages whose page numbers appear in the list of 
numbers and ranges, separated by commas.  A range N-M means 
pages N through M; an initial -N means from the beginning 
to page N; and a final N- means N to the end.  [-o]
07This option is to specify an alternate first page number.  Automatic 
numbering will be performed if no argument is given. [-n]
08nroff will stop after specified number of pages (default is 1) to
allow paper loading or changing and will resume upon receipt of a
line-feed or new-line.  This option does not work i the output of
nroff is piped through col.  When nroff halts between pages, an 
ASCII BEL character is sent to the terminal.  [-s]
09This option sets register a (which must have a one-character 
name) to N.  An example of this is to set a user defined 
register to a value.  If the user input would be b3, the 
command line would have -rb3 included.  This sets the 
register b to the value three.  [-r]
10This option tells nroff to read from standard 
input after input files are exhausted.  [-i]
11This option invokes the simultaneous input/output
mode of the .rd nroff request.  [-q]
12This option prints only messages generated by 
the .tm (terminal message) requests.  [-z]
13This option produces equally-spaced words in
adjusted lines, using the full resolution of
the particular terminal.  [-e]
14This option uses output tabs during horizontal spacing to 
speed output and reduce output character count.  Tab settings
are assumed to be every eight nominal character widths.  [-h]
15The number specified to this argument sets the number of character
overstrikes for the third font position bold) to the amount 
specified or to zero if no number is specified.  [-u]
16ASSIST appends anything you type here to the command line.  
You can use this field for "piping," "redirection," or to 
execute a command in the background.  However, since ASSIST
does not perform any error checking on this field, you should
use it with caution.



030949n
041143n
051355n
061550all
0717421
0819301
102365n
112569n
122762n
132949n
143157n

0015-
003420001010
0107
0103
0304yYnN
0404yYnN
0504yYnN
0608all--,-,----123456789
063410101010
0708
0808123456789
0908
1004yYnN
1104yYnN
1204yYnN
1304yYnN
1404yYnN
1508


001110
011010> 
021010-T
031011y-mmY-mmnN
041011y-manY-mannN
051011y-mptxY-mptxnN
061010-oall
071010-n1
081010-s1
091110-r
101011y-iY-inN
111011y-qY-qnN
121011y-zY-znN
131011y-eY-enN
141011y-hY-hnN
151010-u
161110



