.TH MATH 5
.SH NAME
math \- math functions and constants
.SH SYNOPSIS
.B #include <math.h>
.SH DESCRIPTION
This file contains declarations of all the functions in the
Math Library (described in Section 3M),
as well as various functions in the C Library (Section 3C)
that return floating-point values.
.P
It defines the structure and constants used by the
.IR matherr (3M)
error-handling mechanisms, including
the following constant used as an
error-return value:
.P
.TP 20
.SM
HUGE
The maximum value of a single-precision floating-point number.
.P
The following mathematical constants are defined for user convenience:
.P
.TP 20
.SM
M_E
The base of natural logarithms
.RI ( e ).
.TP 20
.SM
M_LOG2E
The base-2 logarithm of
.IR e .
.TP 20
.SM
M_LOG10E
The base-10 logarithm of
.IR e .
.TP 20
.SM
M_LN2
The natural logarithm of 2.
.TP 20
.SM
M_LN10
The natural logarithm of 10.
.TP 20
.SM
M_PI
The ratio of the circumference of a circle to its diameter.
(There are also several fractions of its reciprocal and its square root.)
.TP 20
.SM
M_SQRT2
The positive square root of 2.
.TP 20
.SM
M_SQRT1_2
The positive square root of 1/2.
.P
For the definitions of various machine-dependent ``constants,''
see the description of the
.I <values.h>\^
header file.
.SH FILES
/usr/include/math.h
.SH "SEE ALSO"
intro(3), matherr(3M), values(5).
.\"	%W% of %G%
