.TH INTRO 4
.SH NAME
intro \- introduction to file formats
.SH DESCRIPTION
This section outlines the formats of various files.
The C
.B struct
declarations for the file formats are given where applicable.
Usually, these structures can be found in the
directories
.B /usr/include
or
.BR /usr/include/sys .
.PP
References of the type
.IR name (1M)
refer to entries found in Section 1
of the
.IR "U\s-1NIX\s+1 System V Administrator Reference Manual" .
.\"	%W% of %G%
