.TH ARCV 1
.SH NAME
arcv \- convert archive files from \s-1PDP\s+1-11 to common archive format
.SH SYNOPSIS
.B arcv
infile outfile
.SH DESCRIPTION
.PP
.I Arcv
converts source archive files from the
.SM PDP\*S-11
format to the \s-1UNIX\s+1 System 5.0
portable archive format.
The input archive file
.I infile
is converted to an equivalent output archive file
.I outfile .
Note that there is no conversion of the members of the input archive
file.
.SH FILES
/tmp/arcv\(**
.SH SEE ALSO
ar(1), convert(1), ar(4).
.\"	@(#)arcv.1	5.2 of 5/18/82
