.TH LOGNAME 1
.SH NAME
logname \- get login name
.SH SYNOPSIS
.B logname
.SH DESCRIPTION
.I Logname\^
returns the contents of the environment variable
.SM \fB$LOGNAME\fP,
which is set when a
user logs into the system.
.SH FILES
/etc/profile
.SH SEE ALSO
env(1), login(1), logname(3X), environ(5).
.\"	@(#)logname.1	5.2 of 5/18/82
