#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)who:who.mk	1.1"

#	Makefile for who 

ROOT =

DIR = $(ROOT)/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s $(LDLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = who.mk


MAINS = who

OBJECTS =  who.o

SOURCES =  who.c

ALL:		$(MAINS)

who:		who.o 
	$(CC) $(CFLAGS)  -o who  who.o   $(LDFLAGS)


who.o:		 $(INC)/errno.h $(INC)/sys/errno.h \
		 $(INC)/fcntl.h $(INC)/stdio.h \
		 $(INC)/string.h $(INC)/sys/types.h	\
		 $(INC)/sys/stat.h $(INC)/utmp.h 

GLOBALINCS = $(INC)/errno.h $(INC)/fcntl.h $(INC)/stdio.h \
	$(INC)/string.h $(INC)/sys/errno.h \
	$(INC)/sys/stat.h $(INC)/sys/types.h $(INC)/utmp.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset $(MAINS) $(DIR)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
