#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)fuser:fuser.mk	1.1"

#	Makefile for fuser

ROOT =

DIR = $(ROOT)/etc

INC = $(ROOT)/usr/include

LDFLAGS = -s $(LDLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = fuser.mk

MAINS = fuser

OBJECTS =  fuser.o

SOURCES =  fuser.c

ALL:		$(MAINS)
	
$(MAINS):	fuser.o
		$(CC) $(CFLAGS) -o fuser fuser.o $(LDFLAGS)

fuser.o:	 $(INC)/nlist.h \
		 $(INC)/fcntl.h \
		 $(INC)/pwd.h \
		 $(INC)/stdio.h \
		 $(INC)/sys/param.h \
		 $(INC)/sys/fs/s5param.h \
		 $(INC)/sys/types.h \
		 $(INC)/sys/fs/s5dir.h	\
		 $(INC)/sys/file.h \
		 $(INC)/sys/inode.h \
		 $(INC)/sys/immu.h \
		 $(INC)/sys/psw.h \
		 $(INC)/sys/pcb.h \
		 $(INC)/sys/region.h \
		 $(INC)/sys/sbd.h \
		 $(INC)/sys/proc.h \
		 $(INC)/sys/signal.h \
		 $(INC)/sys/stat.h \
		 $(INC)/sys/sysmacros.h \
		 $(INC)/sys/user.h \
		 $(INC)/sys/var.h \
		 $(INC)/sys/sema.h \
		 $(INC)/sys/comm.h 

GLOBALINCS = $(INC)/fcntl.h \
	$(INC)/nlist.h \
	$(INC)/pwd.h \
	$(INC)/stdio.h \
	$(INC)/sys/comm.h \
	$(INC)/sys/file.h \
	$(INC)/sys/fs/s5dir.h \
	$(INC)/sys/fs/s5param.h \
	$(INC)/sys/immu.h \
	$(INC)/sys/inode.h \
	$(INC)/sys/param.h \
	$(INC)/sys/pcb.h \
	$(INC)/sys/proc.h \
	$(INC)/sys/psw.h \
	$(INC)/sys/region.h \
	$(INC)/sys/sbd.h \
	$(INC)/sys/sema.h \
	$(INC)/sys/signal.h \
	$(INC)/sys/stat.h \
	$(INC)/sys/sysmacros.h \
	$(INC)/sys/types.h \
	$(INC)/sys/user.h \
	$(INC)/sys/var.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset $(MAINS) $(DIR)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)



