/usr/options/cc.name
/bin/cc
/bin/gencc
/bin/list
/lib/cpp
/lib/comp
/usr/include/a.out.h
/usr/include/aouthdr.h
/usr/include/ar.h
/usr/include/assert.h
/usr/include/core.h
/usr/include/ctype.h
/usr/include/curses.h
/usr/include/dial.h
/usr/include/dirent.h
/usr/include/errno.h
/usr/include/fatal.h
/usr/include/fcntl.h
/usr/include/filehdr.h
/usr/include/ftw.h
/usr/include/grp.h
/usr/include/ieeefp.h
/usr/include/ldfcn.h
/usr/include/limits.h
/usr/include/linenum.h
/usr/include/macros.h
/usr/include/malloc.h
/usr/include/math.h
/usr/include/memory.h
/usr/include/mnttab.h
/usr/include/mon.h
/usr/include/nan.h
/usr/include/nlist.h
/usr/include/nsaddr.h
/usr/include/nserve.h
/usr/include/poll.h
/usr/include/prof.h
/usr/include/pwd.h
/usr/include/regexp.h
/usr/include/reloc.h
/usr/include/rje.h
/usr/include/scnhdr.h
/usr/include/search.h
/usr/include/setjmp.h
/usr/include/sgtty.h
/usr/include/signal.h
/usr/include/stand.h
/usr/include/stdio.h
/usr/include/storclass.h
/usr/include/string.h
/usr/include/stropts.h
/usr/include/strselect.h
/usr/include/syms.h
/usr/include/term.h
/usr/include/termio.h
/usr/include/time.h
/usr/include/tiuser.h
/usr/include/tp_defs.h
/usr/include/unctrl.h
/usr/include/unistd.h
/usr/include/ustat.h
/usr/include/utmp.h
/usr/include/values.h
/usr/include/varargs.h
