#ident	"@(#)graf:src/whatis.d/ttoc.w	1.3"





ttoc [_m_m(1) _f_i_l_e]; make textual table of contents

Output is the textual table of contents (TTOC) generated by
the .TC macro of _m_m(1).  The input is assumed to be a _m_m
file that uses the .H family of macros for section headers.
If no _f_i_l_e is given, the standard input is assumed.
