.TH TN85 7 "3B20S only"
.SH NAME
tn85 \- medium speed line printer controller
.SH DESCRIPTION
The \s-1TN\s+1\&85 provides
a parallel interface
to either one or two
medium speed line printers
which can operate at up to 2000
lines per minute
(132 columns per line,
96 character \s-1ASCII\s+1 set).
If two printers are connected to a
.SM TN\*S85,
then the combined throughput
cannot exceed 2000 lines per minute total.
For example,
it can handle two
1000 line per minute printers
or one 2000 line per minute printer.
.SH FILES
/dev/lp\(**
.\"	@(#)tn85.7	5.2 of 5/18/82
