.TH UN53 7 "3B20S only"
.SH NAME
un53 \- \s-1UN\s+1\&53/\s-1TN\s+1\&82 synchronous device interface
.SH DESCRIPTION
The files
.BR un53 \(**
refer to the
.SM UN\*S53
synchronous communications devices.
Each physical
\s-1UN\s+1\&53/\s-1TN\s+1\&82
pair provides for either one high speed (up to 50KB)
or three low speed (up to 9.6KB) synchronous communications line(s).
.PP
The device interface permits simultaneous communication
on multiple logical devices on a single
\s-1UN\s+1\&53/\s-1TN\s+1\&82
pair.
.SH FILES
/dev/un53*	logical communications lines.
.\"	@(#)un53.7	5.2 of 5/18/82
