/*	Copyright (c) 1984 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)as:3b/as_ctype.c	1.3"
#include "as_ctype.h"

unsigned char as_ctype[] = {
/* EOF */ 0,
/* nul */ 0,
/* soh */ 0,
/* stx */ 0,
/* etx */ 0,
/* eot */ 0,
/* enq */ 0,
/* ack */ 0,
/* bel */ 0,
/* bs  */ 0,
/* ht  */ OPC | WS,
/* nl  */ 0,
/* vt  */ 0,
/* np  */ 0,
/* cr  */ 0,
/* so  */ 0,
/* si  */ 0,
/* dle */ 0,
/* dc1 */ 0,
/* dc2 */ 0,
/* dc3 */ 0,
/* dc4 */ 0,
/* nak */ 0,
/* syn */ 0,
/* etb */ 0,
/* can */ 0,
/* em  */ 0,
/* sub */ 0,
/* esc */ 0,
/* fs  */ 0,
/* gs  */ 0,
/* rs  */ 0,
/* us  */ 0,
/* sp  */ OPC | WS,
/*  !  */ HOPC | OPC,
/*  "  */ HOPC | OPC,
/*  #  */ 0,
/*  $  */ HOPC | OPC | IDF,
/*  %  */ HOPC | OPC,
/*  &  */ HOPC | OPC,
/*  '  */ HOPC | OPC,
/*  (  */ HOPC | OPC,
/*  )  */ HOPC | OPC,
/*  *  */ HOPC | OPC,
/*  +  */ HOPC | OPC,
/*  ,  */ 0,
/*  -  */ HOPC | OPC,
/*  .  */ HOPC | OPC | IDF | IDB,
/*  /  */ HOPC | OPC,
/*  0  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  1  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  2  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  3  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  4  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  5  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  6  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  7  */ HOPC | OPC | IDF | HEX | DEC | OCT,
/*  8  */ HOPC | OPC | IDF | HEX | DEC,
/*  9  */ HOPC | OPC | IDF | HEX | DEC,
/*  :  */ HOPC | OPC,
/*  ;  */ 0,
/*  <  */ HOPC | OPC,
/*  =  */ HOPC | OPC,
/*  >  */ HOPC | OPC,
/*  ?  */ HOPC | OPC,
/*  @  */ HOPC | OPC,
/*  A  */ HOPC | OPC | IDF | IDB | HEX,
/*  B  */ HOPC | OPC | IDF | IDB | HEX,
/*  C  */ HOPC | OPC | IDF | IDB | HEX,
/*  D  */ HOPC | OPC | IDF | IDB | HEX,
/*  E  */ HOPC | OPC | IDF | IDB | HEX,
/*  F  */ HOPC | OPC | IDF | IDB | HEX,
/*  G  */ HOPC | OPC | IDF | IDB,
/*  H  */ HOPC | OPC | IDF | IDB,
/*  I  */ HOPC | OPC | IDF | IDB,
/*  J  */ HOPC | OPC | IDF | IDB,
/*  K  */ HOPC | OPC | IDF | IDB,
/*  L  */ HOPC | OPC | IDF | IDB,
/*  M  */ HOPC | OPC | IDF | IDB,
/*  N  */ HOPC | OPC | IDF | IDB,
/*  O  */ HOPC | OPC | IDF | IDB,
/*  P  */ HOPC | OPC | IDF | IDB,
/*  Q  */ HOPC | OPC | IDF | IDB,
/*  R  */ HOPC | OPC | IDF | IDB,
/*  S  */ HOPC | OPC | IDF | IDB,
/*  T  */ HOPC | OPC | IDF | IDB,
/*  U  */ HOPC | OPC | IDF | IDB,
/*  V  */ HOPC | OPC | IDF | IDB,
/*  W  */ HOPC | OPC | IDF | IDB,
/*  X  */ HOPC | OPC | IDF | IDB,
/*  Y  */ HOPC | OPC | IDF | IDB,
/*  Z  */ HOPC | OPC | IDF | IDB,
/*  [  */ HOPC | OPC,
/*  \  */ HOPC | OPC,
/*  ]  */ HOPC | OPC,
/*  ^  */ HOPC | OPC,
/*  _  */ HOPC | OPC | IDF | IDB,
/*  `  */ HOPC | OPC,
/*  a  */ HOPC | OPC | IDF | IDB | HEX,
/*  b  */ HOPC | OPC | IDF | IDB | HEX,
/*  c  */ HOPC | OPC | IDF | IDB | HEX,
/*  d  */ HOPC | OPC | IDF | IDB | HEX,
/*  e  */ HOPC | OPC | IDF | IDB | HEX,
/*  f  */ HOPC | OPC | IDF | IDB | HEX,
/*  g  */ HOPC | OPC | IDF | IDB,
/*  h  */ HOPC | OPC | IDF | IDB,
/*  i  */ HOPC | OPC | IDF | IDB,
/*  j  */ HOPC | OPC | IDF | IDB,
/*  k  */ HOPC | OPC | IDF | IDB,
/*  l  */ HOPC | OPC | IDF | IDB,
/*  m  */ HOPC | OPC | IDF | IDB,
/*  n  */ HOPC | OPC | IDF | IDB,
/*  o  */ HOPC | OPC | IDF | IDB,
/*  p  */ HOPC | OPC | IDF | IDB,
/*  q  */ HOPC | OPC | IDF | IDB,
/*  r  */ HOPC | OPC | IDF | IDB,
/*  s  */ HOPC | OPC | IDF | IDB,
/*  t  */ HOPC | OPC | IDF | IDB,
/*  u  */ HOPC | OPC | IDF | IDB,
/*  v  */ HOPC | OPC | IDF | IDB,
/*  w  */ HOPC | OPC | IDF | IDB,
/*  x  */ HOPC | OPC | IDF | IDB,
/*  y  */ HOPC | OPC | IDF | IDB,
/*  z  */ HOPC | OPC | IDF | IDB,
/*  {  */ HOPC | OPC,
/*  |  */ HOPC | OPC,
/*  }  */ HOPC | OPC,
/*  ~  */ HOPC | OPC,
/* del */ 0,
};
