.TH INTRO 8
.SH NAME
intro \- introduction to system maintenance procedures
.SH DESCRIPTION
This section outlines certain procedures that will be of interest to
those charged with the task of system maintenance.
Included are discussions on such topics as boot procedures,
recovery from crashes, file backups, etc.
.SH BUGS
No manual can take the place of good, solid experience.
.\"	@(#)intro.8	6.2 of 9/6/83
