#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)wall:wall.mk	1.1"

#	Makefile for wall 

ROOT =

DIR = $(ROOT)/etc

INC = $(ROOT)/usr/include

LDFLAGS = -s $(LDLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = wall.mk


MAINS = wall

OBJECTS =  wall.o

SOURCES =  wall.c

ALL:		$(MAINS)

wall:		wall.o 
	$(CC) $(CFLAGS)  -o wall  wall.o   $(LDFLAGS)


wall.o:		 $(INC)/signal.h $(INC)/sys/signal.h \
		 $(INC)/grp.h $(INC)/sys/types.h \
		 $(INC)/sys/stat.h $(INC)/utmp.h \
		 $(INC)/sys/utsname.h $(INC)/sys/dir.h \
		 $(INC)/pwd.h $(INC)/stdio.h \
		 $(INC)/fcntl.h $(INC)/time.h \
		 $(INC)/errno.h $(INC)/sys/errno.h 

GLOBALINCS = $(INC)/errno.h $(INC)/fcntl.h $(INC)/grp.h \
	$(INC)/pwd.h $(INC)/signal.h $(INC)/stdio.h \
	$(INC)/sys/dir.h $(INC)/sys/errno.h \
	$(INC)/sys/signal.h $(INC)/sys/stat.h \
	$(INC)/sys/types.h $(INC)/sys/utsname.h \
	$(INC)/time.h $(INC)/utmp.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset $(MAINS) $(DIR)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
