/*
********************************************************************************
*                         Copyright (c) 1985 AT&T                              *
*                           All Rights Reserved                                *
*                                                                              *
*                                                                              *
*          THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T                 *
*        The copyright notice above does not evidence any actual               *
*        or intended publication of such source code.                          *
********************************************************************************
*/
#ifdef	SCCS_ID
static	char	SCCS_ID[]	= "@(#)table.c	1.2 (Burroughs) 12/15/82";
#endif
# include "mfile2"

# define WPTR TPTRTO|TINT|TLONG|TFLOAT|TDOUBLE|TPOINT|TUNSIGNED|TULONG
# define AWD SNAME|SOREG|SCON|STARNM|STARREG
/* tbl */
# define ANYSIGNED TPOINT|TINT|TLONG|TSHORT|TCHAR
# define ANYUSIGNED TUNSIGNED|TULONG|TUSHORT|TUCHAR
# define ANYFIXED ANYSIGNED|ANYUSIGNED
# define TWORD TINT|TUNSIGNED|TPOINT|TLONG|TULONG
# define NIAWD SNAME|SCON|STARNM
/* tbl */

struct optab  table[] = {

PCONV,	INAREG|INTAREG,
	SAREG|AWD,	TWORD,
	SANY,	TPOINT,
		0,	RLEFT,
		"",
PCONV,  INAREG|INTAREG,
        SAREG|AWD,      ANYFIXED,
        SANY,   TPOINT,
                NAREG|NASL,     RESC1,
                "ZLM, A1\n",

SCONV,	INTAREG,
	STAREG,	TWORD,
	SANY,	TWORD,
	0,	RLEFT,
	"",

SCONV,	INTAREG,
	SAREG|AWD,	TWORD,
	SANY,	TWORD,
		NAREG,	RESC1,
		"\tmovd\tAL, A1\n",

SCONV,	INTAREG,
	SAREG|AWD,  TWORD,
	SANY, TUCHAR|TUSHORT,
        	NAREG|NASL,  RESC1,
        	"\tmovzZRTd\tAL, A1\n",

SCONV,	INTAREG,
	SAREG|AWD,  TWORD,
	SANY, TCHAR|TSHORT,
        	NAREG|NASL,  RESC1,
        	"\tmovxZRTd\tAL, A1\n",

SCONV,	INTAREG,
	SAREG|AWD, TCHAR|TUCHAR|TSHORT|TUSHORT,
	SANY,	TWORD,
		NAREG|NASL,	RESC1,
		"ZLM, A1\n",

SCONV,	INTAREG,
	SAREG|AWD,	TFLOAT,
	SANY,	TDOUBLE,
		NAREG|NASL,	RESC1,
		"Z1F\tmovfl\tAL,A1\n",

SCONV,	INTAREG,
	SAREG|AWD,	TDOUBLE,
	SANY,	TFLOAT,
		NAREG|NASL,	RESC1,
		"TZ1F\tmovlf\tAL, A1\n",

SCONV,	INTAREG,
	STAREG,	TDOUBLE,
	SANY,	TDOUBLE,
		0,	RLEFT,
		"",

SCONV,	INTAREG,
	SAREG|AWD,	TDOUBLE,
	SANY,	TDOUBLE,
		NAREG,	RESC1,
		"\tmovl\tAL, A1\n",

SCONV,	INTAREG,
	SAREG|AWD,	TUCHAR|TUSHORT,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"ZLM, A1\n\tmovdl\tA1,Z1FA1\n",

SCONV,  INTAREG,
        SAREG|AWD,      TUNSIGNED|TULONG,
        SANY,   TDOUBLE|TFLOAT,
                NAREG|NASL,     RESC1,
                "Z1FZu",

SCONV,	INTAREG,
	SAREG|AWD,	ANYFIXED,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"Z1F\tmovZLTl\tAL,A1\n",

SCONV,	INTAREG,
	SCON,   TDOUBLE|TFLOAT,
	SANY,	ANYFIXED,
		NAREG|NASL,	RESC1,
		"\tmovd\tZLf,A1\n",

SCONV,	INTAREG,
	SAREG|AWD,	TDOUBLE|TFLOAT,
	SANY,	ANYFIXED,
		NAREG|NASL,	RESC1,
		"\ttruncZLTd\tAL,A1\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TWORD,
		0,	RNOP,
		"\t.double\tCL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TSHORT|TUSHORT,
		0,	RNOP,
		"\t.word\tCL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TCHAR|TUCHAR,
		0,	RNOP,
		"\t.byte\tCL\n",

GOTO,	FOREFF,
	SCON,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"\tbr\tCL\n",

GOTO,	FOREFF,
	AWD,	TANY,
	SANY,	TANY,
		NAREG,	RNOP,
		"\tmovd\tAL, A1\n\tjump\tA1\n",

GOTO,	FOREFF,
	SAREG,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"\tjump\tAL\n",

STASG,	FORARG,
	SAREG|AWD,	TANY,
	SAREG|AWD,	TANY,
		NAREG,	RNULL,
		"\tadjspZV\nZS",

STASG,	FOREFF,
	SAREG|AWD,	TANY,
	SAREG|AWD,	TANY,
		NAREG,	RNOP,
		"ZS",

STASG,	INTAREG,
	SAREG|AWD,	TANY,
	SAREG|AWD,	TANY,
		NAREG,	RESC1,
		"ZS\taddr\tAR, A1\n",

OPLOG,	INTAREG,
	SAREG|AWD,	TSHORT|TUSHORT,
	SSCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZJZQd\tA1\n",

OPLOG,	INTAREG,
	SAREG|AWD,	TCHAR|TUCHAR,
	SCCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZJZQd\tA1\n",

OPLOG,	INTAREG,
	SAREG|AWD,	TWORD,
	SCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZJZQd\tA1\n",

OPLOG,	INTAREG,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		NAREG,	RESC1,
		"\tcmpd\tAL,AR\nZQd\tA1\n",
OPLOG,	INTAREG,
	SAREG|AWD,	TSHORT,
	SAREG|AWD,	TSHORT,
		NAREG,	RESC1,
		"\tcmpw\tAL,AR\nZQd\tA1\n",
OPLOG,	INTAREG,
	SAREG|AWD,	TUSHORT,
	SAREG|AWD,	TUSHORT,
		NAREG,	RESC1,
		"\tcmpw\tAL,AR\nZQd\tA1\n",
OPLOG,	INTAREG,
	SAREG|AWD,	TCHAR,
	SAREG|AWD,	TCHAR,
		NAREG,	RESC1,
		"\tcmpb\tAL,AR\nZQd\tA1\n",

OPLOG,	INTAREG,
	SAREG|AWD,	TUCHAR,
	SAREG|AWD,	TUCHAR,
		NAREG,	RESC1,
		"\tcmpb\tAL,AR\nZQd\tA1\n",

OPLOG,	FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SSCON,	TANY,
		0,	RESCC,
		"ZJZP",

OPLOG,	FORCC,
	SAREG|AWD,	TCHAR|TUCHAR,
	SCCON,	TANY,
		0,	RESCC,
		"ZJZP",

OPLOG,	FORCC,
	SAREG|AWD,	TWORD,
	SCON,	ANYFIXED,
		0,    	RESCC,
		"ZJZP",

OPLOG,	FORCC,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		0,	RESCC,
		"\tcmpd\tAL,AR\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TSHORT,
	SAREG|AWD,	TSHORT,
		0,	RESCC,
		"\tcmpw\tAL,AR\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TUSHORT,
	SAREG|AWD,	TUSHORT,
		0,	RESCC,
		"\tcmpw\tAL,AR\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TCHAR,
	SAREG|AWD,	TCHAR,
		0,	RESCC,
		"\tcmpb\tAL,AR\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TUCHAR,
	SAREG|AWD,	TUCHAR,
		0,	RESCC,
		"\tcmpb\tAL,AR\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RESCC,
		"\tcmpl\tAL,AR\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RESCC,
		"\tcmpf\tAL,AR\nZP",

CCODES,  INAREG|INTAREG,
	SANY, TANY,
	SANY, TANY,
		NAREG,	RESC1,
		"\tmovqd\t1,A1\nZN",

UNARY CALL,	INTAREG,
	SCON,	TANY,
	SANY,	TWORD|TCHAR|TUCHAR|TSHORT|TUSHORT|TFLOAT|TDOUBLE,
		NAREG|NASL,	RESC1, /* should be register 0 */
		"\tjsr\tCL\n",

UNARY CALL,	INTAREG,
	AWD,    TANY,
	SANY,	TWORD|TCHAR|TUCHAR|TSHORT|TUSHORT|TFLOAT|TDOUBLE,
		NAREG|NASL,	RESC1, /* should be register 0 */
		"\tmovd\tAL,A1\n\tjsr\tA1\n",

UNARY CALL,	INTAREG,
	SAREG,  TANY,
	SANY,	TWORD|TCHAR|TUCHAR|TSHORT|TUSHORT|TFLOAT|TDOUBLE,
		NAREG|NASL,	RESC1, /* should be register 0 */
		"\tjsr\tAL\n",

INCR,	INTAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZLM, A1\nZE, AL\nZLU",

INCR,	FOREFF,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"TZE, AL\nZLU",

INCR,	FORCC,
	SAREG|AWD,	TCHAR|TUCHAR|TSHORT|TUSHORT,
	SCON,	ANYFIXED,
		NAREG,	RESCC,
		"ZLM, A1\n\tcmpqd\t0, A1\nZrZE, AL\nZLU",

INCR,	FORCC,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,    	RESCC,
		"\tcmpqZLT\t0, AL\nZrZE, AL\nZLU",

INCR,	FORARG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0, RNULL,
		"ZLM, tos\nZE, AL\nZLU",

INCR,	FOREFF,
	SAREG|AWD,	TFLOAT|TDOUBLE,
	SCON,	TANY,
		0, RNULL,
		"\taddZLT\tAR, AL\n",

DECR,	INTAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZLM, A1\nZD, AL\nZLU",

DECR,	FOREFF,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"TZD, AL\nZLU",

DECR,	FORCC,
	SAREG|AWD,	TCHAR|TUCHAR|TSHORT|TUSHORT,
	SCON,	ANYFIXED,
		NAREG,	RESCC,
                "ZLM, A1\n\tcmpqd\t0, A1\nZrZD, AL\nZLU",

DECR,	FORCC,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,    	RESCC,
                "\tcmpqZLT\t0, AL\nZrZD, AL\nZLU",

DECR,	FORARG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0, RNULL,
		"ZLM, tos\nZD, AL\nZLU",

DECR,	FOREFF,
	SAREG|AWD,	TFLOAT|TDOUBLE,
	SCON,	TANY,
		0, RNULL,
		"\tsubZLT\tAR, AL\n",

/* assignment node is all done */
ASSIGN,	FOREFF,
	SAREG|AWD,	ANYFIXED,
	SAREG|AWD,	ANYFIXED,
		0,	RLEFT,
		"ZO",

ASSIGN,	FOREFF,
	SAREG|AWD,	ANYFIXED,
	SAREG|AWD,	ANYFIXED,
		0,	RLEFT,
		"ZO",

ASSIGN,	INTAREG,
	SAREG|AWD,	ANYFIXED,
	SAREG|AWD,	ANYFIXED,
		NAREG,	RESC1,
		"ZOZLM, A1\n",

ASSIGN, FORARG,
	SAREG|AWD,	ANYFIXED,
	SAREG|AWD,	ANYFIXED,
		0,	RNULL,
		"ZOZLM, tos\n",

ASSIGN,	INAREG|FOREFF,
	SAREG|AWD,	ANYFIXED,
	SAREG|AWD,	ANYFIXED,
		0,	RLEFT,
		"TZO",

ASSIGN,	INAREG|FOREFF,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		0,	RLEFT,
		"\tmovfl\tAR,AL\n",

ASSIGN,	INAREG|FOREFF,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT,
		"\tmovlf\tAR,AL\n",

ASSIGN,	INAREG|FOREFF,
	SAREG|AWD,	TANY,
	SAREG|AWD,	TANY,
		0,	RLEFT,
		"\tmovZLT\tAR, AL\n",

ASSIGN,	FOREFF|INAREG,
	SFLD,	TANY,
	SAREG|AWD,	TANY,
		NAREG,	RLEFT,
		"ZH",

UNARY MUL, FOREFF,
	SCC, TANY,
	SCC, TANY,
		0, RNULL,
		"HELP HELP HELP\n",

REG,  INTEMP,
	SANY, TANY,
	SAREG,	TWORD,
		NTEMP,	RESC1,
		"\tmovd\tAR,A1\n",

#ifdef FORT
REG,	INTEMP,
	SANY,	TANY,
	SAREG,	TFLOAT,
		NTEMP,	RESC1,
		"\tmovf\tAR,A1\n",
#endif

REG,	INTEMP,
	SANY,	TANY,
	SAREG,	TDOUBLE,
		2*NTEMP,	RESC1,
		"Z1F\tmovl\tAR,A1\n",

OPLEAF,	FOREFF,
	SANY,	TANY,
	SAREG|AWD,	TANY,
		0,	RRIGHT,
		"",

FLD,	FORCC,
	SAREG|AWD,	TANY,
	SANY, 	TANY,
		NAREG,	RESCC,
		"ZG\tcmpqd\t0, A1\nZr",

FLD,	INAREG|INTAREG,
	SAREG|AWD,	TANY,
	SANY,	TANY,
		NAREG,	RESC1,
		"ZG",

FLD,	FORARG,
	SAREG|AWD,	TANY,
	SANY,	TANY,
		NAREG,	RNULL,
		"ZG\tmovd\tA1, tos\n",

OPLTYPE, FORCC,
	SANY,	TANY,
	SANY,	TCHAR|TUCHAR|TSHORT|TUSHORT,
		NAREG,	RESCC,
		"ZRM, A1\n\tcmpqd\t0, A1\nZr",

OPLTYPE, FORCC,
	SANY,	TANY,
	SANY,	ANYFIXED,
		0,	RESCC,
		"\tcmpqZRT\t0, AR\nZr",

OPLTYPE, FORCC,
	SANY, TANY,
	SANY, TANY,
		0, RESCC,
		"\tcmpZRT\tAR, $0\n",

OPLTYPE, INAREG|INTAREG,
	SANY, TANY,
	SANY, ANYFIXED,
		NAREG|NASR, RESC1,
	"ZRM, A1\n",

OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TDOUBLE,
		NAREG|NASR,	RESC1,
		"Z1F\tmovl\tAR,A1\n",

OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TFLOAT,
		NAREG|NASR,	RESC1,
		"Z1F\tmovfl\tAR,A1\n",

OPLTYPE,	FORARG,
	SANY, TANY,
	SAREG|AWD,  ANYFIXED,
		0, RNULL,
	"ZRM, tos\n",

OPLTYPE,	FORARG,
	SANY,	TANY,
	SAREG|AWD,	TDOUBLE,
		0,	RNULL,
		"\tmovl\tAR, tos\n",

OPLTYPE,	FORARG,
	SANY,	TANY,
	SAREG|AWD,	TFLOAT,
		0,	RNULL,
		"\tmovfl\tAR, tos\n",

UNARY MINUS,	INTAREG,
	SAREG|AWD,	TWORD,
	SANY,	TANY,
		NAREG|NASL,	RESC1,
		"\tnegd\tAL,A1\n",

UNARY MINUS, 	INTAREG,
	SAREG|AWD,	TDOUBLE,
	SANY,	TANY,
		NAREG|NASL,	RESC1,
		"Z1F\tnegl\tAL,A1\n",

UNARY MINUS,	FORCC,
	SAREG|AWD,	TWORD,
	SANY,	TANY,
		NAREG|NASL,	RESCC,
		"\tnegd\tAL,A1\n\tcmpqd\t0, A1\nZr",

UNARY MINUS,	FORCC,
	SAREG|AWD,	TDOUBLE,
	SANY,	TANY,
		NAREG|NASL,	RESCC,
		"Z1F\tnegl\tAL,A1\n\tcmpl\tA1,$0\n",

COMPL,	INTAREG,
	SAREG|AWD,	TWORD,
	SANY,	TANY,
		NAREG|NASL,	RESC1,
		"\tcomZLT\tAL,A1\n",

COMPL,	FORCC,
	SAREG|AWD,	TWORD,
	SANY,	TANY,
		NAREG|NASL,	RESCC,
		"\tcomd\tAL,A1\n\tcmpqd\t0, A1\nZr",

ASG PLUS,	INTAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZE, AL\nZLUZLM, A1\n",

ASG PLUS,	FOREFF|INAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"TZE, AL\nZLU",

ASG PLUS,	FORCC,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
	0,	RESCC,
		"ZE, AL\nZLU\tcmpqZLT\t0, AL\nZr",

ASG PLUS,	FORARG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,	RNULL,
		"ZE, AL\nZLUZLM, tos\n",

ASG MINUS,	INTAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZD, AL\nZLUZLM, A1\n",

ASG MINUS,	FOREFF|INAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"TZD, AL\nZLU",

ASG MINUS,	FORCC,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
	0,	RESCC,
		"ZD, AL\nZLU\tcmpqZLT\t0, AL\nZr",

ASG MINUS,	FORARG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		0,	RNULL,
		"ZD, AL\nZLUZLM, tos\n",

ASG RS, INAREG|FOREFF,
	SAREG|AWD,  ANYSIGNED,
	SAREG|AWD,  TWORD,
		NAREG|NASR, RLEFT,
		"T\tnegd\tAR,A1\n\tashZLT\tA1,AL\nZLU",

ASG RS, INAREG|FOREFF,
	SAREG|AWD,  ANYUSIGNED,
	SAREG|AWD,  TWORD,
		NAREG|NASR, RLEFT,
		"T\tnegd\tAR,A1\n\tlshZLT\tA1,AL\nZLU",

ASG LS, INAREG|FOREFF,
	SAREG|AWD,  ANYSIGNED,
	SAREG|AWD,  TWORD,
		0, RLEFT,
		"T\tashZLT\tAR,AL\nZLU",

ASG LS, INAREG|FOREFF,
	SAREG|AWD,  ANYUSIGNED,
	SAREG|AWD,  TWORD,
		0, RLEFT,
		"T\tlshZLT\tAR,AL\nZLU",

/* the following group of ineficient templates is to circumvent the
	div bug in the ns32 cpu < OPDIV  ODDVALUE, SNAME > */
/* there turns out to be a problem with mul as well */

ASG OPDIV, 	INAREG|FOREFF,
	AWD,		TWORD,
	SAREG|AWD,	TSHORT|TUSHORT|TCHAR|TUCHAR,
		2*NAREG,	RESC1,
		"\tmovd\tAL, A1\nZRM, A2\n\tOL\tA2, A1\n\tmovd\tA1, AL\n",

ASG OPDIV, 	INAREG|FOREFF,
	AWD,		ANYFIXED,
	SCON,		ANYFIXED,
		NAREG,	RESC1,
		"ZLM, A1\n\tOL\tAR, A1\n\tmovZLT\tA1, AL\n",

ASG OPDIV, 	INAREG|FOREFF,
	AWD,		TWORD,
	SAREG|AWD,	TWORD,
		NAREG,	RESC1,
		"ZLM, A1\n\tOL\tAR, A1\n\tmovZLT\tA1, AL\n",

ASG OPDIV, 	INAREG|FOREFF,
	AWD,	TSHORT|TUSHORT,
	SAREG|AWD,	TSHORT|TUSHORT,
		2*NAREG,	RESC1,
		"ZLM, A1\nZRM, A2\n\tOL\tA2, A1\n\tmovw\tA1, AL\n",

ASG OPDIV,	INAREG|FOREFF,
	AWD,	TCHAR|TUCHAR,
	SAREG|AWD,	TCHAR|TUCHAR,
		2*NAREG,	RESC1,
		"ZLM, A1\nZRM, A2\n\tOL\tA2, A1\n\tmovb\tA1, AL\n",

ASG OPMUL, 	INAREG|FOREFF,
	AWD,		TWORD,
	SAREG|AWD,	TSHORT|TUSHORT|TCHAR|TUCHAR,
		2*NAREG,	RESC1,
		"\tmovd\tAL, A1\nZRM, A2\n\tOL\tA2, A1\n\tmovd\tA1, AL\n",

ASG OPMUL, 	INAREG|FOREFF,
	AWD,		ANYFIXED,
	SCON,		ANYFIXED,
		NAREG,	RESC1,
		"ZLM, A1\n\tOL\tAR, A1\n\tmovZLT\tA1, AL\n",

ASG OPMUL, 	INAREG|FOREFF,
	AWD,		TWORD,
	SAREG|AWD,	TWORD,
		NAREG,	RESC1,
		"ZLM, A1\n\tOL\tAR, A1\n\tmovZLT\tA1, AL\n",

ASG OPMUL, 	INAREG|FOREFF,
	AWD,	TSHORT|TUSHORT,
	SAREG|AWD,	TSHORT|TUSHORT,
		2*NAREG,	RESC1,
		"ZLM, A1\nZRM, A2\n\tOL\tA2, A1\n\tmovw\tA1, AL\n",

ASG OPMUL,	INAREG|FOREFF,
	AWD,	TCHAR|TUCHAR,
	SAREG|AWD,	TCHAR|TUCHAR,
		2*NAREG,	RESC1,
		"ZLM, A1\nZRM, A2\n\tOL\tA2, A1\n\tmovb\tA1, AL\n",

/* end of special fix */

ASG OPMUL,	INAREG|FOREFF,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		0,	RLEFT,
		"\tOL\tAR,AL\nZLU",

ASG OPMUL,	INAREG|FOREFF,
	SAREG|AWD,	TSHORT|TUSHORT,
	SAREG|AWD,	TSHORT|TUSHORT,
		0,	RLEFT,
		"T\tOW\tAR,AL\nZLU",

ASG OPMUL,	INAREG|FOREFF,
	SAREG|AWD,	TSHORT|TUSHORT,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"T\tOW\tAR,AL\nZLU",

ASG OPMUL,	INAREG|FOREFF,
	SAREG|AWD,	TCHAR|TUCHAR,
	SAREG|AWD,	TCHAR|TUCHAR,
		0,	RLEFT,
		"T\tOB\tAR,AL\nZLU",

ASG OPMUL,	INAREG|FOREFF,
	SAREG|AWD,	TCHAR|TUCHAR,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"T\tOB\tAR,AL\nZLU",

ASG OPMUL,	INAREG|FOREFF,
	SAREG|AWD,	 TWORD,
	SAREG|AWD,	TSHORT|TUSHORT|TCHAR|TUCHAR,
		NAREG|NASR,	RLEFT,
		"ZRM,A1\n\tOL\tA1,AL\nZLU",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		0,	RLEFT,
		"\tOL\tAR,AL\nZLU",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	TSHORT|TUSHORT,
	SAREG|AWD,	TSHORT|TUSHORT,
		0,	RLEFT,
		"T\tOW\tAR,AL\nZLU",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	TSHORT|TUSHORT,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"T\tOW\tAR,AL\nZLU",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	TCHAR|TUCHAR,
	SAREG|AWD,	TCHAR|TUCHAR,
		0,	RLEFT,
		"T\tOB\tAR,AL\nZLU",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	TCHAR|TUCHAR,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"T\tOB\tAR,AL\nZLU",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	 TWORD,
	SAREG|AWD,	TSHORT|TUSHORT|TCHAR|TUCHAR,
		NAREG|NASR,	RLEFT,
		"ZRM,A1\n\tOL\tA1,AL\nZLU",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT,
		"\tdivl\tAR,AL\n",

ASG OPDIV,	INAREG|FOREFF,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG|NASR,	RLEFT,
		"Z1F\tmovfl\tAR,A1\n\tdivl\tA1,AL\n",

ASG OPFLOAT,	INAREG|FOREFF,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT,
		"\tOD\tAR,AL\n",

ASG OPFLOAT,	INAREG|FOREFF,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG|NASR,	RLEFT,
		"Z1F\tmovfl\tAR,A1\n\tOD\tA1,AL\n",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		0,	RLEFT,
		"\tOL\tAR,AL\nZLU",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG|AWD,	TSHORT|TUSHORT,
	SAREG|AWD,	TSHORT|TUSHORT,
		0,	RLEFT,
		"T\tOW\tAR,AL\nZLU",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG|AWD,	TSHORT|TUSHORT,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"T\tOW\tAR,AL\nZLU",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG|AWD,	TCHAR|TUCHAR,
	SAREG|AWD,	TCHAR|TUCHAR,
		0,	RLEFT,
		"T\tOB\tAR,AL\nZLU",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG|AWD,	TCHAR|TUCHAR,
	SCON,	ANYFIXED,
		0,	RLEFT,
		"T\tOB\tAR,AL\nZLU",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TSHORT|TUSHORT|TCHAR|TUCHAR,
		NAREG|NASR,	RLEFT,
		"ZRM,A1\n\tOL\tA1,AL\nZLU",

PLUS, INAREG|INTAREG,
	SBREG,	TWORD,
	SCON,	 TWORD,
		NAREG, RESC1,
		"\taddr\tCR(AL), A1\n",

MINUS, INAREG|INTAREG,
	SBREG,	TWORD,
	SCON,	 TWORD,
		NAREG, RESC1,
		"\taddr\t-CR(AL), A1\n",

PLUS, INAREG|INTAREG,
	STAREG,  ANYFIXED,
	SCON, ANYFIXED,
		0, RLEFT,
	"ZE, AL\n",

PLUS,	INAREG|INTAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZKZE, A1\n",

MINUS, INAREG|INTAREG,
	STAREG,  ANYFIXED,
	SCON, ANYFIXED,
		0, RLEFT,
	"ZD, AL\n",

MINUS,	INAREG|INTAREG,
	SAREG|AWD,	ANYFIXED,
	SCON,	ANYFIXED,
		NAREG,	RESC1,
		"ZKZD, A1\n",

RS,	INAREG|INTAREG,
	STAREG,  TINT|TLONG,
	SAREG|AWD,  TWORD,
		NAREG|NASR, RLEFT,
		"\tnegd\tAR,A1\n\tashd\tA1,AL\n",

RS,	INAREG|INTAREG,
	STAREG,  TUNSIGNED|TULONG,
	SAREG|AWD,  TWORD,
		NAREG|NASR, RLEFT,
		"\tnegd\tAR,A1\n\tlshd\tA1,AL\n",

RS,	INAREG|INTAREG,
	SAREG|AWD,  TINT|TLONG,
	SAREG|AWD,  TWORD,
		2*NAREG,	RESC1,
		"\tnegd\tAR,A2\n\tmovd\tAL,A1\n\tashd\tA2,A1\n",

RS,	INAREG|INTAREG,
	SAREG|AWD,  TUNSIGNED|TULONG,
	SAREG|AWD,  TWORD,
		2*NAREG,	RESC1,
		"\tnegd\tAR,A2\n\tmovd\tAL,A1\n\tlshd\tA2,A1\n",

LS,	INAREG|INTAREG,
	STAREG,  TINT|TLONG,
	SAREG|AWD,  ANYFIXED,
		0, RLEFT,
		"\tashd\tAR,AL\n",

LS,	INAREG|INTAREG,
	STAREG,  TUNSIGNED|TULONG,
	SAREG|AWD,  ANYFIXED,
		0, RLEFT,
		"\tlshd\tAR,AL\n",

LS,	INAREG|INTAREG,
	SAREG|AWD,  TINT|TLONG,
	SAREG|AWD,  ANYFIXED,
		NAREG,	RESC1,
		"\tmovd\tAL,A1\n\tashd\tAR,A1\n",

LS,	INAREG|INTAREG,
	SAREG|AWD,  TUNSIGNED|TULONG,
	SAREG|AWD,  ANYFIXED,
		NAREG,	RESC1,
		"\tmovd\tAL,A1\n\tlshd\tAR,A1\n",

OPMUL,	INAREG|INTAREG,
	STAREG,	TWORD,
	SAREG|AWD,	TWORD,
		0,	RLEFT,
		"\tOL\tAR,AL\n",

OPMUL,	INAREG|INTAREG,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		NAREG,  RESC1,
		"ZLM,A1\n\tOL\tAR,A1\n",

OPDIV,	INAREG|INTAREG,
	STAREG,	TWORD,
	SAREG|AWD,	TWORD,
		0,	RLEFT,
		"\tOL\tAR,AL\n",

OPDIV,	INAREG|INTAREG,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		NAREG,  RESC1,
		"ZLM,A1\n\tOL\tAR,A1\n",

OPDIV,	INAREG|INTAREG,
	STAREG,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT,
		"\tdivl\tAR,AL\n",

OPDIV,	INAREG|INTAREG,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RESC1,
		"Z1F\tmovl\tAL,A1\n\tdivl\tAR,A1\n",

OPFLOAT,	INAREG|INTAREG,
	STAREG,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT,
		"\tOD\tAR,AL\n",

OPFLOAT,	INAREG|INTAREG,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RESC1,
		"Z1F\tmovl\tAL,A1\n\tOD\tAR,A1\n",

OPSIMP,	INAREG|INTAREG,
	STAREG,	TWORD,
	SAREG|AWD,	TWORD,
		0,	RLEFT,
		"\tOL\tAR,AL\n",

OPSIMP,	INAREG|INTAREG,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		NAREG,  RESC1,
		"ZLM,A1\n\tOL\tAR,A1\n",

	/* Default actions for hard trees ... */

# define DF(x) FORREW,SANY,TANY,SANY,TANY,REWRITE,x,""

UNARY MUL, DF( UNARY MUL ),

INCR, DF(INCR),

DECR, DF(INCR),

ASSIGN, DF(ASSIGN),

STASG, DF(STASG),

FLD, DF(FLD),

OPLEAF, DF(NAME),

OPLOG,	FORCC,
	SANY,	TANY,
	SANY,	TANY,
		REWRITE,	BITYPE,
		"",

OPLOG,	DF(NOT),

COMOP, DF(COMOP),

INIT, DF(INIT),

OPUNARY, DF(UNARY MINUS),


ASG OPANY, DF(ASG PLUS),

OPANY, DF(BITYPE),

FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	"help; I'm in trouble\n" };
