/*	Copyright (c) 1984 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)comp:u3b/table.c	1.23.2.1"
/*	@(#) table.c: 1.23.2.1 10/10/85	*/
# include "mfile2"

# define WPTR TPTRTO|TINT|TLONG|TPOINT|TUNSIGNED|TULONG
# define AWD SNAME|SOREG|SCON|STARNM
# define ANYSIGNED TPOINT|TINT|TLONG|TSHORT|TCHAR
# define ANYUSIGNED TUNSIGNED|TULONG|TUSHORT|TUCHAR
# define ANYFIXED ANYSIGNED|ANYUSIGNED
# define TWORD TINT|TUNSIGNED|TPOINT|TLONG|TULONG

struct optab  table[] = {

PCONV,	INAREG|INTAREG,
	SAREG|AWD,	TCHAR|TUCHAR|TSHORT|TUSHORT,
	SANY,	TPOINT,
		NAREG|NASL,	RESC1,
		"	movZlZLw	AL,A1\n",


PCONV,	INAREG|INTAREG,
	SAREG|AWD,	TWORD,
	SANY,	TPOINT,
		NAREG|NASL,	RESC1,
		"",

# ifdef FLT
PCONV,	INAREG|INTAREG,
	SAREG|AWD,	TFLOAT|TDOUBLE,
	SANY,		TPOINT,
		NAREG,	RESC1,
		"	movaw	AL,A1\n",

#ifdef SPFORT
SCONV,	INTAREG|FORCC,
	SAREG|AWD,	TLONG|TINT|TUNSIGNED,
	SANY,	TFLOAT,
		NAREG|NASL,	RESC1|RESCC,
		"	movws	AL,A1T\n",
#endif

SCONV,	INTAREG|FORCC,
	SAREG|AWD,	TUNSIGNED|TULONG,
	SANY,	TFLOAT|TDOUBLE,
		NAREG|NASL,	RESC1|RESCC,
		"ZW",

SCONV,	INTAREG|FORCC,
	SAREG|AWD,		TLONG|TINT,
	SANY,		TFLOAT|TDOUBLE,
	NAREG|NASL,		RESC1|RESCC,
		"	movwd	AL,A1\n",

SCONV,	INTAREG|FORCC,
	SAREG|AWD,		TFLOAT|TDOUBLE,
	SANY,		TINT|TUNSIGNED|TLONG,
	NAREG|NASL,		RESC1|RESCC,
		"	movtZLTw	AL,A1\n",


SCONV,	INTAREG|FORCC,
	AWD|SAREG,		TFLOAT|TDOUBLE,
	SANY,			TFLOAT|TDOUBLE,
	NAREG|NASL,			RESC1|RESCC,
		"	movZLZRT	AL,A1\n",

#ifdef SPFORT

SCONV,	INTAREG|FORCC,
	AWD,	TCHAR|TSHORT,
	SANY,	TFLOAT|TDOUBLE,
	NAREG|NASL,	RESC1|RESCC,
	"	movbZLw	AL,A1\n	movwZRT	A1,A1\n",

SCONV,	INTAREG|FORCC,
	AWD,	TUCHAR|TUSHORT,
	SANY,	TFLOAT|TDOUBLE,
	NAREG|NASL,	RESC1|RESCC,
	"	movzZLw	AL,A1\n	movwZRT	A1,A1\n",

SCONV,	INTAREG|FORCC,
	SAREG|AWD,	TFLOAT,
	SANY,	TDOUBLE,
		NAREG|NASL,	RESC1|RESCC,
		"	movsd	AL,A1\n",
#endif /*SPFORT*/

SCONV,	INTAREG|FORCC,
#	ifdef SPFORT
	AWD,	TANY,
#	else
	SAREG,		TANY,
#	endif /*SPFORT*/
	SANY,		TFLOAT|TDOUBLE,
	NAREG|NASL,	RESC1|RESCC,
	"	movw	AL,A1\n	movwZRT	A1,A1\n",

# endif /*FLT*/


SCONV,  INTAREG|FORCC,
        SAREG|AWD,      TWORD,
        SANY,   TUSHORT,
                NAREG|NASL,     RESC1|RESCC,
                "	Zs\n",

/* kwick kludge 6/21 */
SCONV,	INTAREG,
	STAREG,	TCHAR|TUCHAR,
	SANY,	TCHAR|TUCHAR,
		0,	RLEFT,
		"",

SCONV,	INTAREG,
	STAREG,	TSHORT|TUSHORT,
	SANY,	TSHORT|TUSHORT,
		0,	RLEFT,
		"",

SCONV,	INTAREG,
	STAREG,	TWORD,
	SANY,	TWORD,
		NAREG|NASL,	RLEFT,
		"",

/* end kwick kludge */

SCONV,	INTAREG|INTAREG|FORCC,
	SAREG|SNAME|SCON|STARNM|SAREG,	TANY,
	SANY,		TANY,
		NAREG|NASL,	RESC1|RESCC,
		"	movZlZLZR	AL,A1\n",

SCONV,	INTAREG|INTAREG|FORCC,
# ifdef INDEX
	SSOREG,	TANY,
# else
	SOREG,	TANY,
# endif
	SANY,	TANY,
		NAREG|NASL,	RESC1|RESCC,
		"	movZlZLZR	AL,A1\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TWORD,
		0,	RNOP,
		"	.word	CL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TSHORT|TUSHORT,
		0,	RNOP,
		"	.half	CL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TCHAR|TUCHAR,
		0,	RNOP,
		"	.byte	CL\n",


#ifdef FORT
		/* special operators for fortran only */

GOTO,	FOREFF,
	SCON,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"	jmp	CL\n",

GOTO,	FOREFF,
	AWD,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"	jmp	*AL\n",

GOTO,	FOREFF,
	SAREG,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"	jmp	0(AL)\n",

#endif /*FORT*/

STARG,	INTEMP,
	SCON|SAREG,	TANY,
	SANY,	TANY,
		NTEMP,	RESC1,
		"ZS",

STASG,	FORARG,	/* set up by genargs() */
	SOREG,	TANY,
	SSTCALL,	TANY,
		0,	RNULL,
		"	movaw	-ZcAL,%r2\nZE",

STASG,	FORARG,	/* set up by genargs() */
	SOREG,	TANY,
	SCON|SAREG,	TANY,
		0,	RNULL,
		"ZS",

STASG,	INAREG|FOREFF,
	SNAME|SOREG,	TANY,
	SSTCALL,	TANY,
		0,	RRIGHT,
		"	movaw	AL,%r2\nZE",

STASG,	FOREFF,
	SNAME|SOREG,	TANY,
	SCON|SAREG,	TANY,
		0,	RNOP,
		"ZS",

STASG,	INAREG,
	SNAME|SOREG,	TANY,
	SCON,	TANY,
		NAREG,	RESC1,
		"ZS	movw	AR,A1\n",

STASG,	INAREG,
	SNAME|SOREG,	TANY,
	SAREG,	TANY,
		0,	RRIGHT,
		"	pushw	AR\nZS	movw	-4(%sp),AR\n	subw2	&4,%sp\n",	/* rather sloppy */

FLD,	INAREG|INTAREG,
	SANY,	TANY,
	SFLD,	TANY,
		NAREG|NASR,	RESC1,
		"	extzv	&H,&S,AR,A1\n",

OPLOG,	FORCC,
	SAREG|SAREG|AWD,	TWORD,
	SAREG|SAREG|AWD,	TWORD,
		0,	RESCC,
		"	ZQw	AL,AR\nZP",

OPLOG,	FORCC,
	SAREG|SAREG|AWD,	TSHORT|TUSHORT,
	SAREG|SAREG|AWD,	TSHORT|TUSHORT,
		0,	RESCC,
		"	ZQh	AL,AR\nZP",

OPLOG,	FORCC,
	SAREG|SAREG|AWD,	TCHAR|TUCHAR,
	SAREG|SAREG|AWD,	TCHAR|TUCHAR,
		0,	RESCC,
		"	ZQb	AL,AR\nZP",

OPLOG,	FORCC,
	SAREG|SAREG|AWD,	TSHORT|TUSHORT,
	SSCON,	TANY,
		0,	RESCC,
		"	ZQh	AL,AR\nZP",

OPLOG,	FORCC,
	SAREG|SAREG|AWD,	TCHAR|TUCHAR,
	SCCON,	TANY,
		0,	RESCC,
		"	ZQb	AL,AR\nZP",

# ifdef FLT

#ifdef SPFORT

OPLOG,	FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RESCC,
		"	fcmps	AL,AR\nZP",

#endif /*SPFORT*/

OPLOG,	FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		NAREG|NASL,	RESCC,
		"	movsd	AL,A1\n	fcmpd	A1,AR\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG|NASR,	RESCC,
		"	movsd	AR,A1\n	fcmpd	AL,A1\nZP",

OPLOG,	FORCC,
	SAREG|AWD,	TFLOAT|TDOUBLE,
	SAREG|AWD,	TFLOAT|TDOUBLE,
		0,	RESCC,
		"	ZQZR	AL,AR\nZP",
# endif /*FLT*/

CCODES,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TANY,
		NAREG,	RESC1,
		"ZN",

# ifdef TV
UNARY CALL,	INTAREG,
	SCON,	TANY,
	STV,	TWORD|TCHAR|TUCHAR|TSHORT|TUSHORT,
		NAREG,	RESC1, /* should be R0 */
		"	.tv	CL\n	call	ZC,*CL\n",
# endif /*TV*/

#ifdef SPFORT
UNARY CALL,	INTAREG,
	SCON,	TANY,
	SNOTTV,	TFLOAT,
		NAREG,	RESC1,	/* R0 */
		"	call	ZC,CLT\n",

UNARY CALL,	INTAREG,
	SAREG,	TANY,
	SANY,	TFLOAT,
		NAREG|NASL,	RESC1,
		"ZT0(AL)T\n",

UNARY CALL,	INTAREG,
	SNAME,	TANY,
	SANY,	TFLOAT,
		NAREG,	RESC1,
		"	call	ZC,*ALT\n",

UNARY CALL,	INTAREG,
#ifdef INDEX
	SSOREG,	TANY,
#else
	SOREG,	TANY,
#endif
	SANY,	TFLOAT,
		NAREG|NASL,	RESC1,
		"	call	ZC,*ALT\n",
#endif /*SPFORT*/

UNARY CALL,	INTAREG,
	SCON,	TANY,
	SNOTTV,	TANY,
		NAREG,	RESC1, /* should be R0 */
		"	call	ZC,CL\n",

UNARY CALL,	INTAREG,
	SAREG,	TANY,
	SANY,	TANY,
		NAREG|NASL,	RESC1,	/* should be R0 */
		"ZT0(AL)\n",

UNARY CALL,	INTAREG,
	SNAME,	TANY,
	SANY,	TANY,
		NAREG,	RESC1,	/* should be R0 */
		"	call	ZC,*AL\n",

UNARY CALL,	INTAREG,
# ifdef INDEX
	SSOREG,	TANY,
# else
	SOREG,	TANY,
# endif
	SANY,	TANY,
		NAREG|NASL,	RESC1,	/* should be R0 */
		"	call	ZC,*AL\n",


# ifdef TV
UNARY STCALL,	INTEMP|FOREFF|INTAREG,
	SCON,	TANY,
	STV,	TANY,
		NTEMP+NAREG,	RESC1,	/* should be R0 */
		"	movaw	A2,%r2\n	.tv	CL\n	call	ZC,*CL\n",
# endif /*TV*/

UNARY STCALL,	INTEMP|FOREFF|INTAREG,
	SCON,	TANY,
	SNOTTV,	TANY,
		NTEMP+NAREG,	RESC1,	/* should be R0 */
		"	movaw	A2,%r2\n	call	ZC,CL\n",

UNARY STCALL,	INTEMP|FOREFF|INTAREG,
	SAREG,	TANY,
	SANY,	TANY,
		NTEMP+NAREG|NASL,	RESC1,	/* should be R0 */
		"	movaw	A2,%r2\nZT0(AL)\n",

UNARY STCALL,	INTEMP|FOREFF|INTAREG,
	SNAME,	TANY,
	SANY,	TANY,
		NTEMP+NAREG,	RESC1,	/* should be R0 */
		"	movaw	A2,%r2\n	call	ZC,*AL\n",
	

ASG RS,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|SCON,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	lrsw2	AR,AL\n",

ASG RS,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TCHAR|TUCHAR,
		0,	RLEFT|RESCC,
		"	lrsw2	AR,AL\n",

RS,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|SCON,	ANYFIXED,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	lrsw3	AR,AL,A1\n",

RS,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TCHAR|TUCHAR,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	lrsw3	AR,AL,A1\n",

ASG LS,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|SCON,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	llsw2	AR,AL\n",

ASG LS,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TCHAR|TUCHAR,
		0,	RLEFT|RESCC,
		"	llsw2	AR,AL\n",

LS,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|SCON,	ANYFIXED,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	llsw3	AR,AL,A1\n",

LS,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TCHAR|TUCHAR,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	llsw3	AR,AL,A1\n",

# ifdef FLT

#ifdef SPFORT

INCR,	FOREFF,
	SAREG|AWD|SAREG,	TFLOAT|TDOUBLE,
	SANY,			TANY,
		0,	RLEFT,
		"	faddZL2	AR,AL\nT",

#else

INCR,	FOREFF,
	SAREG|AWD,	TFLOAT,
	SANY,	TANY,
		NAREG|NASR,	RLEFT,
		"	movZRs	AR,A1\n	fadds2	A1,AL\n",

INCR,	FOREFF,
	SAREG|AWD|SAREG,	TDOUBLE,
	SANY,			TANY,
		0,	RLEFT,
		"	faddZL2	AR,AL\n",

#endif /*SPFORT*/

# endif /*FLT*/

INCR,	FOREFF,
	SAREG|AWD,	TANY,
	SANY,	TANY,
		0,	RLEFT,
		"	addZL2	AR,AL\n",

# ifdef FLT

#ifdef SPFORT

DECR,	FOREFF,
	SAREG|AWD|SAREG,	TFLOAT|TDOUBLE,
	SANY,	TANY,
		0,	RLEFT,
		"	faddZL2	AR,AL\nT",

#else

DECR,	FOREFF,
	SAREG|AWD,	TFLOAT,
	SCON,	TANY,
		NAREG|NASR,	RLEFT,
		"	movZRs	AR,A1\n	fsubs2	A1,AL\n",

DECR,	FOREFF,
	SAREG|AWD|SAREG,	TDOUBLE,
	SCON,	TANY,
		0,	RLEFT,
		"	fsubZL2	AR,AL\n",

#endif /*SPFORT*/

# endif /*FLT*/

DECR,	FOREFF,
	SAREG|AWD,	TANY,
	SCON,	TANY,
		0,	RLEFT,
		"	subZL2	AR,AL\n",

INCR,	INAREG|INTAREG,
	SAREG|AWD,	TANY,
	SCON,	TANY,
		NAREG,	RESC1,
		"	ZD\n	addZL2	AR,AL\n",

DECR,	INAREG|INTAREG,
	SAREG|AWD,	TANY,
	SCON,	TANY,
		NAREG,	RESC1,
		"	ZD\n	subZL2	AR,AL\n",

/* Seems to be problems through the ASSIGN stuff related to
 * reclaiming everything in sight and using the T to turn off
 * repainting register types.
 *
 * 3/9/83:
 * First phase--don't reclaim RRIGHT with T macro on.
 */

#ifdef FLT

/* get double = double and float = float INAREG first */

ASSIGN,	INAREG,
	STARNM,	TFLOAT,
	SAREG,	TFLOAT,
		NAREG,	RRIGHT,
		"	ZAT\n",

ASSIGN,	INAREG,
	STARNM,	TDOUBLE,
	SAREG,	TDOUBLE,
		NAREG,	RRIGHT,
		"	ZAT\n",

ASSIGN,	INAREG|FOREFF|FORCC,
	STARNM,	TFLOAT|TDOUBLE,
	SAREG,	TANY,
		NAREG,	RLEFT|RESCC,
		"	ZAT\n",

ASSIGN,	INAREG|FOREFF|FORCC,
	SAREG,	TANY,
	STARNM,	TFLOAT|TDOUBLE,
		NAREG,	RLEFT|RESCC,
		"	ZAT\n",

/* reverse the order, rather reclaim AREG when both apply */

ASSIGN,	INAREG|FOREFF|FORCC,
	SAREG,	TANY,
	SAREG|AWD,	TFLOAT|TDOUBLE,
		0,	RLEFT|RESCC,
		"	ZAT\n",

ASSIGN,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TFLOAT|TDOUBLE,
	SAREG,	TANY,
		0,	RLEFT|RESCC,
		"	ZAT\n",

#endif /*FLT*/

ASSIGN,	FOREFF|FORCC,
	STARNM,	TANY,
	STARNM,	TANY,
		2*NAREG,	RLEFT|RESCC,
		"	ZAT\n",

ASSIGN, INTAREG,
	SAREG|AWD,	TWORD,
	STAREG,	TWORD,
		0,	RRIGHT,
		"	ZA\n",

ASSIGN,	INAREG,
	SAREG,	ANYFIXED,
	SAREG|AWD,	ANYFIXED,
		0,	RLEFT,
		"	ZA\n",

/* cya when reclaiming the right side */
ASSIGN,	INAREG,
	AWD,	TCHAR|TUCHAR,
	STAREG,	TSHORT|TUSHORT|TWORD,
		0,	RRIGHT,
		"	ZA\n	movtZRb	AR,AR\n",

ASSIGN,	INAREG,
	AWD,	TSHORT|TUSHORT,
	STAREG,	TWORD,
		0,	RRIGHT,
		"	ZA\n	movtZRh	AR,AR\n",

ASSIGN,	INAREG,
	AWD,	TWORD,
	SAREG,	TWORD,
		0,	RRIGHT,
		"	ZA\n",

ASSIGN,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TANY,
	SAREG|AWD,	TANY,
		0,	RLEFT|RESCC,
		"	ZAT\n",

/* make all the 3ADR guys FOREFF|FORCC only unless sure lhs is AREG */

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SW3ADR,	TANY,
		0,	RESCC,
		"	Z3,AL\n",

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SH3ADR,	TANY,
		0,	RESCC,
		"	Z3,AL\n",

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TCHAR|TUCHAR,
	SB3ADR,	TANY,
		0,	RESCC,
		"	Z3,AL\n",

ASSIGN,	INAREG,
	SAREG,	TWORD,
	SW3ADR,	TANY,
		0,	RLEFT,
		"	Z3,AL\n",
	
ASSIGN,	INAREG,
	SAREG,	TSHORT|TUSHORT,
	SH3ADR,	TANY,
		0,	RLEFT,
		"	Z3,AL\n",

ASSIGN,	INAREG,
	SAREG,	TCHAR|TUCHAR,
	SB3ADR,	TANY,
		0,	RLEFT,
		"	Z3,AL\n",

#ifdef FLT

#ifdef SPFORT

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SD3ADR,	TDOUBLE,
		0,	RESCC,
		"	fZ3,AL\n",

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TFLOAT,
	SW3ADR,	TFLOAT,
		0,	RESCC,
		"	fZ3,AL\n",

ASSIGN,	INAREG,
	SAREG,	TDOUBLE,
	SD3ADR,	TDOUBLE,
		0,	RLEFT,
		"	fZ3,AL\n",

ASSIGN,	INAREG,
	SAREG,	TFLOAT,
	SW3ADR,	TFLOAT,
		0,	RLEFT,
		"	fZ3,AL\n",

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SW3ADR,	TFLOAT,
		0,	RESCC,
		"	fZ3,AL\n	movsd	AL,AL\n",

ASSIGN,	INAREG,
	SAREG,	TDOUBLE,
	SW3ADR,	TFLOAT,
		0,	RLEFT,
		"	fZ3,AL\n	movsd	AL,AL\n",

/* break in pattern--add INTAREG on this one and reclaim (forced double)
 * in RESC1
 */

/* Z3 passes type of assign down to triadic (probably a mistake there), 
/* since this template is an "optimization", just scratch it
/*
/*ASSIGN,	INTAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TFLOAT,
/*	SD3ADR,	TDOUBLE,
/*		2*NAREG,	RESC1|RESCC,
/*		"	fZ3,A1\n	movds	A1,AL\n",
*/

#else

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SD3ADR,	TDOUBLE,
		0,	RESCC,
		"	fZ3,AL\n",

ASSIGN,	INAREG,
	SAREG,	TDOUBLE,
	SD3ADR,	TDOUBLE,
		0,	RLEFT,
		"	fZ3,AL\n",

#endif /*SPFORT*/

#endif /*FLT*/

/* again, do the same thing for S2ADR clowns */

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SW2ADR,	TANY,
		0,	RESCC,
		"	Z2,AL\n",

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SH2ADR,	TANY,
		0,	RESCC,
		"	Z2,AL\n",

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TCHAR|TUCHAR,
	SB2ADR,	TANY,
		0,	RESCC,
		"	Z2,AL\n",

ASSIGN,	INAREG,
	SAREG,	TWORD,
	SW2ADR,	TANY,
		0,	RLEFT,
		"	Z2,AL\n",

ASSIGN,	INAREG,
	SAREG,	TSHORT|TUSHORT,
	SH2ADR,	TANY,
		0,	RLEFT,
		"	Z2,AL\n",

ASSIGN,	INAREG,
	SAREG,	TCHAR|TUCHAR,
	SB2ADR,	TANY,
		0,	RLEFT,
		"	Z2,AL\n",

#ifdef FLT

/* reclaim lhs, don't T on SAREG */

ASSIGN,	INAREG|FOREFF|FORCC,
	SAREG,	TWORD,
	SSCONV,	TANY,
		0,	RLEFT|RESCC,
		"	ZFZA\n",

ASSIGN,	INAREG|FOREFF|FORCC,
	AWD,	TWORD,
	SSCONV,	TANY,
		0,	RLEFT|RESCC,
		"	ZFZAT\n",

ASSIGN,	INAREG|FOREFF|FORCC,
	AWD,	TFLOAT|TDOUBLE,
	SSCONV,	TANY,
		0,	RLEFT|RESCC,
		"	ZFZAT\n",

/* special for SPFORT--reclaim a float in lhs AREG */

ASSIGN,	INAREG,
#ifdef SPFORT
	SAREG,	TFLOAT|TDOUBLE,
#else
	SAREG,	TDOUBLE,
#endif /*SPFORT*/
	SSCONV,	TANY,
		0,	RLEFT,
		"	ZFZAT\n",

#endif FLT

/* ok, got all of the cutesy cases, now bludgeon it to death */
/* this one is last to catch all of the assignments in "value" context */
/* reclaim the lhs even though it's not where you want it--it'll turn */
/* into an OPLTYPE with which we can cope. */

ASSIGN,	INAREG,
	AWD,	TANY,
	AWD,	TANY,
		0,	RLEFT,
		"	ZA\n",

/* bitfields */

ASSIGN,	FOREFF|FORCC,
	SFLD,	TANY,
	SAREG|AWD,	TWORD,
		0,	RESCC,
		"	insv	AR,&H,&S,AL\n",

ASSIGN,	INAREG,
	SFLD,	TANY,
	SAREG|AWD,	TWORD,
		0,	RRIGHT,
		"	insv	AR,&H,&S,AL\n",

ASSIGN,	FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SFLD,	TANY,
		0,	RESCC,
		"	extzv	&H,&S,AR,AL\n",

ASSIGN,	INAREG,
	SAREG|AWD,	TWORD,
	SFLD,	TANY,
		0,	RLEFT,
		"	extzv	&H,&S,AR,AL\n",

/*# ifdef FLT
/*ASSIGN, INAREG|FOREFF|FORCC,
/*	STARNM,	TFLOAT|TDOUBLE,
/*	SAREG,	TANY,
/*		NAREG,	RRIGHT|RLEFT|RESCC,
/*		"	ZAT\n",
/*
/*ASSIGN, INAREG|FOREFF|FORCC,
/*	SAREG,	TANY,
/*	STARNM,	TFLOAT|TDOUBLE,
/*		NAREG,	RRIGHT|RLEFT|RESCC,
/*		"	ZAT\n",
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TFLOAT|TDOUBLE,
/*	SAREG,		TANY,
/*		0,	RRIGHT|RLEFT|RESCC,
/*		"	ZAT\n",
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG,		TANY,
/*	SAREG|AWD,	TFLOAT|TDOUBLE,
/*		0,	RLEFT|RRIGHT|RESCC,
/*		"	ZAT\n",
/*# endif /*FLT*/
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	STARNM,	TANY,
/*	STARNM,	TANY,
/*		2*NAREG,	RLEFT|RRIGHT|RESCC,
/*		"	ZAT\n",
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TANY,
/*	SAREG|AWD,	TANY,
/*		0,	RLEFT|RRIGHT|RESCC,
/*		"	ZAT\n",
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TWORD,
/*	SW3ADR,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	Z3,AL\n",
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TSHORT|TUSHORT,
/*	SH3ADR,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	Z3,AL\n",
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TCHAR|TUCHAR,
/*	SB3ADR,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	Z3,AL\n",
/*
/*# ifdef FLT
/*
/*#ifdef SPFORT
/*
/*ASSIGN,	INTAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TDOUBLE,
/*	SD3ADR,	TDOUBLE,
/*		0,	RLEFT|RESCC,
/*		"	fZ3,AL\nT",
/*
/*ASSIGN,	INTAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TFLOAT,
/*	SD3ADR,	TFLOAT,
/*		0,	RLEFT|RESCC,
/*		"	fZ3,AL\nT",
/*
/*ASSIGN,	INTAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TDOUBLE,
/*	SD3ADR,	TFLOAT,
/*		0,	RLEFT|RESCC,
/*		"	fZ3,AL\n	movsd	AL,AL\n",
/*
/*ASSIGN,	INTAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TFLOAT,
/*	SD3ADR,	DOUBLE,
/*		NAREG,	RLEFT|RESCC,
/*		"	fZ3,A1\n	movds	A1,AL\n",
/*#else
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TDOUBLE,
/*	SD3ADR,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	fZ3,AL\n",
/*
/*#endif /*SPFORT*/
/*
/*# endif /*FLT*/
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TWORD,
/*	SW2ADR,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	Z2,AL\n",
/*
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TSHORT|TUSHORT,
/*	SH2ADR,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	Z2,AL\n",
/*
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TCHAR|TUCHAR,
/*	SB2ADR,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	Z2,AL\n",
/*
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SFLD,	TANY,
/*	SAREG|AWD,	TWORD,
/*		0,	RRIGHT|RESCC,
/*		"	insv	AR,&H,&S,AL\n",
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG|AWD,	TWORD,
/*	SFLD,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	extzv	&H,&S,AR,AL\n",
/*
/*# ifdef FLT
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG,	TINT|TLONG,
/*	SSCONV,		TANY,
/*		0,	RLEFT|RESCC,
/*		"	ZFZAT\n",
/*
/*ASSIGN,	FOREFF|FORCC,
/*	AWD,	TINT|TLONG,
/*	SSCONV,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	ZFZAT\n",
/*
/*
/*ASSIGN,	INAREG|FOREFF|FORCC,
/*	SAREG,	TFLOAT|TDOUBLE,
/*	SSCONV,		TANY,
/*		0,	RLEFT|RESCC,
/*		"	ZFZAT\n",
/*
/*ASSIGN,	FOREFF|FORCC,
/*	AWD,	TFLOAT|TDOUBLE,
/*	SSCONV,	TANY,
/*		0,	RLEFT|RESCC,
/*		"	ZFZAT\n",
/*# endif /*FLT*/

/* dummy UNARY MUL entry to get U* to possibly match OPLTYPE */

UNARY MUL,	FOREFF,
	SCC,	TANY,
	SCC,	TANY,
		0,	RNULL,
		"	HELP HELP HELP\n",

# ifdef FLT


REG,	INTEMP,
	SANY,	TANY,
	SAREG|SAREG,	TDOUBLE,
		2*NTEMP,	RESC1,
#ifdef MOVD
		"	movd	AR,A1\n",
#else /*MOVD*/
		"	Zm\n",
#endif /*MOVD*/

REG,	INTEMP,
	SANY,	TANY,
	SAREG|SAREG,	TFLOAT,
		NTEMP,	RESC1,
		"	movw	AR,A1\n",

# endif /*FLT*/


REG,	INTEMP,
	SANY,	TANY,
	SAREG,	TANY,
		NTEMP,	RESC1,
		"	movw	AR,A1\n",

OPLEAF,	FOREFF,
	SANY,	TANY,
	SAREG|AWD|SAREG,	TANY,
		0,	RLEFT,
		"",

# ifdef FLT
#ifndef SPFORT
OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TFLOAT,
		NAREG|NASR,	RESC1,
		"	movsd	AR,A1\n",
#endif /*SPFORT*/

/*
OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TFLOAT|TDOUBLE,
		NAREG|NASR,	RESC1,
		"	TZA\n",
*/

/*
* OPLTYPE,	INAREG|INTAREG,
*	SANY,	TANY,
*	SANY,	TDOUBLE,
*		NAREG+NAREG,		RESC1+RESC2,
*		"	ZZ\n",
*/

#ifdef SPFORT
OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TFLOAT,
		NAREG,	RESC1,
		"	movw	AR,A1T\n",
#endif /*SPFORT*/

# endif /*FLT*/

OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TUSHORT|TUCHAR|TCHAR,	/* chars ALWAYS unsigned... */
		NAREG|NASR,	RESC1,
		"	movzZRw	AR,A1\n",

OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TSHORT,
		NAREG|NASR,	RESC1,
		"	movbhw	AR,A1\n",

OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	ANYFIXED|TFLOAT,
		NAREG|NASR,	RESC1,
		"	movw	AR,A1\n",

OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TDOUBLE,
#ifdef MOVD
		NAREG|NASR,	RESC1,
		"	movd	AR,A1\n",
#else /*MOVD*/
		NAREG,	RESC1,
		"	Zm\n",
#endif /*MOVD*/

# ifdef FLT
OPLTYPE,	FORCC,
	SANY,	TANY,
	SANY,	TFLOAT|TDOUBLE,
		0,	RESCC,
		"	ZQZR	AR,&0.0\n",
# endif /*FLT*/

OPLTYPE,	FORCC,
	SANY,	TANY,
	SANY,	TANY,
		0,	RESCC,
		"	ZQZR	AR,&0\n",

#ifdef SPFORT
OPLTYPE,	FORARG,
	SANY,	TANY,
	SANY,	TWORD,
		0,	RNULL,
		"	ZB",
#endif /*SPFORT*/

OPLTYPE,	FORARG,
	SANY,	TANY,
	SANY,	ANYFIXED,
		0,	RNULL,
		"	pushZrZR	AR\n",

# ifdef FLT
# ifndef MOVD
OPLTYPE,	FORARG,
	SANY,	TANY,
	SANY,	TFLOAT|TDOUBLE,
		NAREG|NASR,	RNULL,
		"	Zp\n",
# else /*MOVD*/

OPLTYPE,	FORARG,
	SANY,	TANY,
	SANY,	TDOUBLE,
		0,	RNULL,
		"	pushd	AR\n",
# endif /*MOVD*/

OPLTYPE,	FORARG,
	SANY,	TANY,
	SANY,	TFLOAT,
		NAREG|2*NTEMP,	RNULL,
		"	movsd	AR,A1\n	pushd	A1\n",

UNARY MINUS,	INTAREG|FORCC,
	SAREG|AWD,	TDOUBLE,
	SANY,		TANY,
		NAREG,	RESC1|RESCC,
		"	fsubd3	AL,&0.0,A1\n",

#ifdef SPFORT
UNARY MINUS,	INTAREG|FORCC,
#else
UNARY MINUS,	FORCC,
#endif
	SAREG|AWD,	TFLOAT,
	SANY,		TANY,
		NAREG,	RESC1|RESCC,
		"	Tfsubs3	AL,&0.0,A1\n",

UNARY MINUS,	INTAREG,
	SAREG|AWD,	TFLOAT,
	SANY,	TANY,
		NAREG|NASL,	RESC1|RESCC,
		"	movsd	AL,A1\n	fsubd3	A1,&0.0,A1\n",
# endif /*FLT*/

UNARY MINUS,	INTAREG|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SANY,	TANY,
		NAREG|NASL,	RESC1|RESCC,
		"	mnegZL	AL,A1\n",

COMPL,	INTAREG|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SANY,	TANY,
		NAREG|NASL,	RESC1|RESCC,
		"	mcomZL	AL,A1\n",

AND,	FORCC,
	SAREG|AWD,	TWORD,
	SCON,	TWORD,
		0,	RESCC,
		"	bitw	AR,AL\n",

AND,	FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SSCON,	TWORD,
		0,	RESCC,
		"	bith	AR,AL\n",

AND,	FORCC,
	SAREG|AWD,	TCHAR|TUCHAR,
	SCCON,	TWORD,
		0,	RESCC,
		"	bitb	AR,AL\n",

ASG OPDIV,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	ZUOW2	AR,AL\n",

# ifdef FLT

#ifdef SPFORT

ASG OPDIV,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RLEFT|RESCC,
		"T	OS2	AR,AL\n",

#endif /*SPFORT*/

ASG OPDIV,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n	movds	A1,AL\n",

ASG OPDIV,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESCC,
		"	movwd	AL,A1\n	OD2	AR,A1\n	movtdw	A1,AL\n",

ASG OPDIV,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TUNSIGNED,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESCC,
		"ZW	OD2	AR,A1\n	movtdw	A1,AL\n",

ASG OPDIV,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG,	RLEFT|RESCC,
		"	movsd	AR,A1\n	OD2	A1,AL\n",

ASG OPDIV,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT,
	SAREG|AWD,	TFLOAT,
		2*NTEMP+NAREG,	RLEFT|RESCC,
		"	movwd	AL,A2\n	movsd	AR,A1\n	OD2	A1,A2\n	movtdw A2,AL\n",

ASG OPDIV,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TUNSIGNED,
	SAREG|AWD,	TFLOAT,
		2*NTEMP+NAREG,	RLEFT|RESCC,
		"ZW	movsd	AR,A2\n	OD2	A2,A1	\n	 movtdw	A1,AL\n",

ASG OPDIV,	FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",

ASG OPDIV,	INTAREG,
	STAREG,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",
# endif /*FLT*/

OPDIV,	INAREG|INTAREG|FORCC,
	STAREG,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	ZUOW2	AR,AL\n",

OPDIV,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	ZUOWZ1\n",

# ifdef FLT

#ifdef SPFORT

OPDIV,	INTAREG|FORCC,
	STAREG,		TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RLEFT|RESCC,
		"T	OS2	AR,AL\n",

OPDIV,	INTAREG|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	OSZ1\nT",

#endif /*SPFORT*/

OPDIV,	INTAREG|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		NAREG|NASL,	RESC1|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n",

OPDIV,	INTAREG|FORCC,
	STAREG,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG,	RLEFT|RESCC,
		"	movsd	AR,A1\n	OD2	A1,AL\n",

OPDIV,	INTEMP,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		2*NTEMP,	RESC1|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n",

OPDIV,	INTAREG|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG|NASR,	RESC1|RESCC,
		"	movsd	AR,A1\n	OD3	A1,AL,A1\n",

OPDIV,	INTEMP,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		2*NTEMP,	RESC1|RESCC,
		"	movsd	AR,A1\n	OD3	A1,AL,A1\n",

OPDIV,	INTAREG|FORCC,
	STAREG,		TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",

OPDIV,	INTAREG|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RESC1|RESCC,
		"	ODZ1\n",

OPDIV,	INTEMP,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		2*NTEMP,	RESC1|RESCC,
		"	ODZ1\n",
# endif /*FLT*/

ASG OPMUL,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	ZUOW2	AR,AL\n",

# ifdef FLT

ASG OPMUL,	INAREG|FOREFF|FORCC,
	SAREG|SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG|SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	ZUOW2	AR,AL\n",

#ifdef SPFORT

ASG OPMUL,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RLEFT|RESCC,
		"T	OS2	AR,AL\n",

#endif /*SPFORT*/

ASG OPMUL,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n	movds	A1,AL\n",

ASG OPMUL,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESCC,
		"	movwd	AL,A1\n	OD2	AR,A1\n	movtdw	A1,AL\n",

ASG OPMUL,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TUNSIGNED,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESCC,
		"ZW	OD2	AR,A1\n	movtdw	A1,AL\n",

ASG OPMUL,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG,	RLEFT|RESCC,
		"	movsd	AR,A1\n	OD2	A1,AL\n",
	
ASG OPMUL,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT,
	SAREG|AWD,	TFLOAT,
		2*NTEMP+NAREG,	RLEFT|RESCC,
		"	movwd	AL,A1\n	movsd	AR,A2\n	OD2	A1,A2\n	movtdw	A2,AL\n",
	
ASG OPMUL,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TUNSIGNED,
	SAREG|AWD,	TFLOAT,
		2*NTEMP+NAREG,	RLEFT|RESCC,
		"ZW	movsd	AR,A2\n	OD2	A1,A2\n	movtdw	A2,AL\n",
	
ASG OPMUL,	FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",

ASG OPMUL,	INTAREG,
	STAREG,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",

# endif /*FLT*/

OPMUL,	INAREG|INTAREG|FORCC,
	STAREG,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	ZUOW2	AR,AL\n",

OPMUL,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG|AWD,	TINT|TUNSIGNED|TLONG|TULONG,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	ZUOWZ1\n",

# ifdef FLT

#ifdef SPFORT

OPMUL,	INTAREG|FORCC,
	STAREG,		TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RLEFT|RESCC,
		"T	OS2	AR,AL\n",

OPMUL,	INTAREG|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	OSZ1\nT",

#endif /*SPFORT*/

OPMUL,	INTAREG|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		NAREG|NASL,	RESC1|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n",

OPMUL,	INTEMP,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		2*NTEMP,	RESC1|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n",

OPMUL,	INTAREG|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG|NASR,	RESC1|RESCC,
		"	movsd	AR,A1\n	OD2	AL,A1\n",

OPMUL,	INTEMP,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		2*NTEMP,	RESC1|RESCC,
		"	movsd	AR,A1\n	OD2	AL,A1\n",

OPMUL,	INTAREG|FORCC,
	STAREG,		TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",

OPMUL,	INTAREG|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	ODZ1\n",

OPMUL,	INTEMP,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		2*NTEMP,	RESC1|RESCC,
		"	ODZ1\n",
# endif /*FLT*/

ASG OPSIMP,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|SAREG|AWD,	TWORD,
		0,	RLEFT|RESCC,
		"	OW2	AR,AL\n",

ASG OPSIMP,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SAREG|SAREG|AWD,	TSHORT|TUSHORT,
		0,	RLEFT|RESCC,
		"	OH2	AR,AL\n",

ASG OPSIMP,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SSCON,	TWORD,
		0,	RLEFT|RESCC,
		"	OH2	AR,AL\n",

ASG OPSIMP,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TCHAR|TUCHAR,
	SAREG|SAREG|AWD,	TCHAR|TUCHAR,
		0,	RLEFT|RESCC,
		"	OB2	AR,AL\n",

ASG OPSIMP,	INAREG|FOREFF|FORCC,
	SAREG|AWD,	TCHAR|TUCHAR,
	SCCON,	TWORD,
		0,	RLEFT|RESCC,
		"	OB2	AR,AL\n",

# ifdef FLT

#ifdef SPFORT

ASG OPSIMP,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RLEFT|RESCC,
		"T	OS2	AR,AL\n",

#endif /*SPFORT*/

ASG OPSIMP,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESC1|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n	movds	A1,AL\n",

ASG OPSIMP,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESC1|RESCC,
		"	movwd	AL,A1\n	OD2	AR,A1\n	movtdw	A1,AL\n",

ASG OPSIMP,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TUNSIGNED,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RLEFT|RESC1|RESCC,
		"	ZW	OD2	AR,A1\n	movtdw	A1,AL\n",

ASG OPSIMP,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG,	RLEFT|RESCC,
		"	movsd	AR,A1\n	OD2	A1,AL\n",

ASG OPSIMP,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TINT,
	SAREG|AWD,	TFLOAT,
		2*NTEMP+NAREG,	RLEFT|RESCC,
		"	movwd	AL,A1\n	movsd	AR,A2\n	OD2	A2,A1\n	movtdw	A1,AL\n",

ASG OPSIMP,	INTAREG|FOREFF|FORCC,
	SAREG|AWD,	TUNSIGNED,
	SAREG|AWD,	TFLOAT,
		2*NTEMP+NAREG,	RLEFT|RESCC,
		"ZW	movsd	AR,A2\n	OD2	A2,A1\n	movtdw	A1,AL\n",

ASG OPSIMP,	FOREFF|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",

ASG OPSIMP, 	INTAREG,
	STAREG,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
		"	OD2	AR,AL\n",
# endif /*FLT*/

#ifdef M32
PLUS,	FORARG,
	SAREG,	ANYFIXED,
	SCON,	TWORD,
		0,	RNULL,
		"	pushaw	CR(AL)\n",

#endif /* M32 */

OPSIMP,	INAREG|INTAREG|FORCC,
	STAREG,	ANYFIXED,
	SAREG|AWD,	TWORD,
		0,	RLEFT|RESCC,
		"	OW2	AR,AL\n",

#ifdef M32
PLUS,	INTAREG,
	SAREG,	TWORD,
	SCON,	TWORD,
		NAREG|NASL,	RESC1,
		"	movaw	CR(AL),A1\n",
#endif /* M32 */

OPSIMP,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TWORD,
	SAREG|AWD,	TWORD,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	OWZ1\n",

OPSIMP,	INAREG|INTAREG,
	SAREG|AWD,	TUSHORT,
	SAREG|AWD,	TUSHORT,
		NAREG|NASL|NASR,	RESC1,
		"	OHZ1\n\tmovzhw	A1,A1\n",

OPSIMP,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SAREG|AWD,	TSHORT|TUSHORT,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	OHZ1\n",

OPSIMP,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TUSHORT,
	SSCON,	TWORD,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	OHZ1\n\tmovzhw	A1,A1\n",

OPSIMP,	INAREG|INTAREG|FORCC,
	SAREG|AWD,	TSHORT|TUSHORT,
	SSCON,	TWORD,
		NAREG|NASL|NASR,	RESC1|RESCC,
		"	OHZ1\n",

OPSIMP,	INAREG|INTAREG|FORCC,
	STAREG,	ANYFIXED,
	SAREG,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	OW2	AR,AL\n",

OPSIMP,	INAREG|INTAREG|FORCC,
	STAREG,	ANYFIXED,
	SAREG,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	OW2	AR,AL\n",

OPSIMP,	INAREG|INTAREG|FORCC,
	SAREG|SCON,	ANYFIXED,
	SAREG|SCON,	ANYFIXED,
		NAREG,	RESC1|RESCC,
		"	OWZ1\n",

# ifdef FLT

#ifdef SPFORT

OPSIMP,	INTAREG|FORCC,
	STAREG,		TFLOAT,
	SAREG|AWD,	TFLOAT,
		0,	RLEFT|RESCC,
		"T	OS2	AR,AL\n",

OPSIMP,	INTAREG|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TFLOAT,
		NAREG,	RESC1|RESCC,
		"	OSZ1\nT",

#endif /*SPFORT*/

OPSIMP,	INTAREG|FORCC,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		NAREG|NASL,	RESC1|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n",

OPSIMP,	INTEMP,
	SAREG|AWD,	TFLOAT,
	SAREG|AWD,	TDOUBLE,
		2*NTEMP,	RESC1|RESCC,
		"	movsd	AL,A1\n	OD2	AR,A1\n",

OPSIMP,	INTAREG|FORCC,
	STAREG,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG|NASR,	RLEFT|RESCC,
		"	movsd	AR,A1\n	OD2	A1,AL\n",

OPSIMP,	INTAREG|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		NAREG,	RESC1|RESCC,
		"	movsd	AR,A1\n	OD3	A1,AL,A1\n",

OPSIMP,	INTEMP,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TFLOAT,
		2*NTEMP,	RESC1|RESCC,
		"	movsd	AR,A1\n	OD3	A1,AL,A1\n",

OPSIMP,	INTAREG|FORCC,
	STAREG,		TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		0,	RLEFT|RESCC,
	"	OD2	AR,AL\n",

OPSIMP,	INTAREG|FORCC,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		NAREG,	RESC1|RESCC,
		"	ODZ1\n",

OPSIMP,	INTEMP,
	SAREG|AWD,	TDOUBLE,
	SAREG|AWD,	TDOUBLE,
		2*NTEMP,	RESC1|RESCC,
		"	ODZ1\n",
# endif /*FLT*/
	/* Default actions for hard trees ... */

# define DF(x) FORREW,SANY,TANY,SANY,TANY,REWRITE,x,""

UNARY MUL, DF( UNARY MUL ),

INCR, DF(INCR),

DECR, DF(INCR),

ASSIGN, DF(ASSIGN),

STASG, DF(STASG),

OPLEAF, DF(NAME),

OPLOG,	FORCC,
	SANY,	TANY,
	SANY,	TANY,
		REWRITE,	BITYPE,
		"",

OPLOG,	DF(NOT),

COMOP, DF(COMOP),

INIT, DF(INIT),

FLD, DF(FLD),

OPUNARY, DF(UNARY MINUS),


ASG OPANY, DF(ASG PLUS),

OPANY, DF(BITYPE),

FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	"help; I'm in trouble\n" };
