#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)ff:ff.mk	1.2"

#	Makefile for /etc/ff

ROOT =

DIR = $(ROOT)/etc

INC = $(ROOT)/usr/include

LDFLAGS = -s $(LDLIBS)

CFLAGS = -O -I$(INC) $(FFLAG)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.46

MAKEFILE = ff.mk


MAINS = ff

OBJECTS =  ff.o

SOURCES =  ff.c

ALL:		$(MAINS)

ff:		ff.o 
	$(CC) $(CFLAGS)  -o ff  ff.o   $(LDFLAGS)


ff.o:		 $(INC)/sys/param.h $(INC)/sys/types.h \
		 $(INC)/fcntl.h $(INC)/sys/filsys.h \
		 $(INC)/sys/inode.h $(INC)/sys/ino.h \
		 $(INC)/sys/dir.h $(INC)/sys/stat.h \
		 $(INC)/stdio.h $(INC)/pwd.h 

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset $(MAINS) $(DIR)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo Makefile $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(GLOBALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
