#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)volcopy:volcopy.mk	1.1"

#	Makefile for volcopy

ROOT =

DIR = $(ROOT)/etc

INC = $(ROOT)/usr/include

LDFLAGS = $(LDLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = volcopy.mk

MAINS = volcopy

OBJECTS =  volcopy.o

SOURCES =  volcopy.c

ALL:		$(MAINS)

$(MAINS):	volcopy.o
		$(CC) $(CFLAGS) -o volcopy volcopy.o $(LDFLAGS)

volcopy.o:	 $(INC)/sys/param.h \
		 $(INC)/sys/fs/s5param.h \
		 $(INC)/signal.h \
		 $(INC)/sys/signal.h \
		 $(INC)/sys/types.h \
		 $(INC)/sys/sysmacros.h \
		 $(INC)/sys/filsys.h \
		 $(INC)/sys/fs/s5filsys.h \
		 $(INC)/sys/stat.h \
		 $(INC)/stdio.h \
		 $(INC)/signal.h \
		 $(INC)/sys/signal.h 

GLOBALINCS = $(INC)/signal.h \
	$(INC)/stdio.h \
	$(INC)/sys/filsys.h \
	$(INC)/sys/fs/s5filsys.h \
	$(INC)/sys/fs/s5param.h \
	$(INC)/sys/param.h \
	$(INC)/sys/signal.h \
	$(INC)/sys/stat.h \
	$(INC)/sys/sysmacros.h \
	$(INC)/sys/types.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset $(MAINS) $(DIR)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
