.TH CHROOT 2
.SH NAME
chroot \- change root directory
.SH SYNOPSIS
.B int chroot (path)
.br
.B char \(**path;
.PP
.SH DESCRIPTION
.I Path\^
points to a
path name
naming a directory.
.I Chroot\^
causes the named directory to become the root directory,
the starting point for path searches for
path names
beginning with
.BR / .
The user's working directory is unaffected by the \f2chroot\fR system call.
.PP
The effective user
.SM ID
of the process must be super-user
to change the root directory.
.PP
The
.B ..
entry in the root directory is interpreted to mean the root directory
itself.
Thus,
.B ..
cannot be used to access files outside the subtree rooted at the root
directory.
.PP
.I Chroot\^
will fail and the root directory will remain unchanged if
one or more of the following are true:
.TP 15
.SM
\%[ENOTDIR]
Any component of the
path name
is not a directory.
.TP
.SM
\%[ENOENT]
The named directory does not exist.
.TP
.SM
\%[EPERM]
The effective user
.SM ID
is not super-user.
.TP
.SM
\%[EFAULT]
.I Path\^
points outside the allocated address space of the process.
.SH "RETURN VALUE"
Upon successful completion, a value of 0 is returned.
Otherwise, a value of \-1 is returned and
.I errno\^
is set to indicate the error.
.SH "SEE ALSO"
chdir(2).
.\"	@(#)chroot.2	6.2 of 9/6/83
