.TH UNAME 2
.SH NAME
uname \- get name of current \s-1UNIX\s0 system
.SH SYNOPSIS
.B #include <sys/utsname.h>
.PP
.B int uname (name)
.br
.B struct utsname \(**name;
.SH DESCRIPTION
.I Uname\^
stores
information identifying the current
.SM UNIX
system in the structure pointed to by
.IR name .
.PP
.I Uname\^
uses the structure
defined in \f3<sys/utsname.h>\fP whose members are:
.PP
.RS
char	sysname[9];
.br
char	nodename[9];
.br
char	release[9];
.br
char	version[9];
.br
char	machine[9];
.RE
.PP
.I Uname\^
returns
a null-terminated character string naming the current
.SM UNIX
system in the character array
.IR sysname .
Similarly,
.I nodename\^
contains the name that the system is known by on a communications
network.
.I Release\^
and
.I version\^
further identify the operating system.
.I Machine\^
contains a standard name that identifies the hardware that
the
.SM UNIX
system is running on.
.PP
.TP \w'[\s-1EFAULT\s+2]\ \ 'u
.TP
.SM
\%[EFAULT]
.I Uname\^
will fail if
.I name\^
points to an invalid address.
.SH "RETURN VALUE"
Upon successful completion, a non-negative value is returned.
Otherwise, \-1 is returned and
.I errno\^
is set to indicate the error.
.SH SEE ALSO
uname(1) in the
\f2\s-1UNIX\s+1 System V User Reference Manual\fR.
.\"	@(#)uname.2	6.2 of 9/6/83
