.\" @(#)ttoc.w	1.1
ttoc [\fImm(\fR1\fI) file\fR]; make textual table
of contents
.sp
Output is the textual table of contents (TTOC)
generated by the .TC macro of \fImm\fR(1).
The input is assumed to be a \fImm\fR file
that uses the .H family of macros for section headers.
If no \fIfile\fR is given, the standard input is
assumed.
